<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/read_pandas_Puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Doing It Like `pandas`

Created by K. Bunchongchit (kritya.bun@mahidol.edu) <br>Last updated on Sept. 22, 2026

Last modified by Jiraroj Wiruchpongsanon (6781617) on 22/09/2026

Most of the time in this class, we'll reading data from files and accessing those data rather than creating our own datasets from unstructured or semi-structured data. Thus, this notebook focuses on the intricacy of read operations in `pandas`. As mentioned before in class, some methods are only available via `Series` and some only via 'DataFrame`. If our operation does not result in the correct type, we cannot apply the property of method that we need to work efficiently. (Of course, there is a way to go around things, but using a trustable, available function will save you time and increase the accuracy of your program.)

In [1]:
import pandas as pd

import pandas library, abridge the library call as 'pd'

In [2]:
df = pd.DataFrame({
    'Gold': [15, 12, 10],
    'Silver': [11, 9, 5] ,
    'Bronze': [6, 8, 12],
    'Continent': ['Europe', 'Asia', 'Asia']
    },
    ['France','China','Thailand'])
df

          Gold  Silver  Bronze Continent
France      15      11       6    Europe
China       12       9       8      Asia
Thailand    10       5      12      Asia

create our main pandas dataframe, using dictionary for column and column index, and list for row index

Below are some examples to demonstrate some property and method that are available only to `pandas Series`.

In [3]:
df.is_monotonic_increasing

AttributeError: 'DataFrame' object has no attribute 'is_monotonic_increasing'

As the assignment description in muic elearning site said, `is_monotonic_increasing` only works on pandas `Series`, it doesn't work on `dataframe`

In [4]:
df['Gold'].is_monotonic_increasing

False

Pick a column out of our `dataframe` as a `Series`, and now, `is_monotonic_increasing` work

In [5]:
df.pct_change()

TypeError: unsupported operand type(s) for /: 'str' and 'str'

Same for `pct_change()`, it didn't work on `dataframe`.

In [6]:
df['Gold'].pct_change()

France           NaN
China      -0.200000
Thailand   -0.166667
Name: Gold, dtype: float64

Has to convert to pandas `Series` first, that `pct_change()` behave as expected.

So, let's dive into solving the puzzles below!

Write code to perform the following subsetting tasks on the DataFrame object `df` declared at the beginning of this notebook with numerical indices and column labels. Subsetting implies that you cannot create a new object from scratch. Using labels implies that you cannot use numerical indices.

## Part I: Getting a Specific Data Type

Use only labels indices/headers in this section. You may use `loc` and other pandas methods, but no numerical indices.

### 1.1 Access 8 as a literal.

In [7]:
df.iloc[1, 2]

np.int64(8)

Access (2, 3) entry on the `dataframe`. We get a scalar in this case.

In [8]:
type(df.iloc[1, 2])

numpy.int64

### 1.2 Access 8 as a Series object and maintain its labels.

In [9]:
df.loc['China', ['Bronze']]

Bronze    8
Name: China, dtype: int64

I usually think of it as, which ever dimension is written as a list, `['Bronze']` (our column) in this case, got to keep it's dimension, else it's dimension will be lost. 

So, in this case, we're left with (1, ), which is a `Series`. 

A `Series` also contain index labels, so that's how the label is present.

In [10]:
type(df.loc['China', ['Bronze']])

pandas.Series

### 1.3 Access 8 as a DataFrame object and maintain its labels.

In [11]:
df.loc[['China'], ['Bronze']]

       Bronze
China       8

As describe in 1.2, for this one, both dimension remain, so we're left with (1, 1), which is a `dataframe`.

In [12]:
type(df.loc[['China'], ['Bronze']])

pandas.DataFrame

## Part II: Subsetting, `loc` and `iloc`

### 2.1 Get the intersection of the last two rows and the last two columns **without** use `loc` and `iloc`.

In [13]:
df[-2:][['Bronze', 'Continent']]

          Bronze Continent
China          8      Asia
Thailand      12      Asia

Do chain indexing, access the left two rows first through slicing, then select the last two column by it's column label

### 2.2 Get the intersection of the last two rows and the last two columns **with at least one** `loc`.

In [14]:
df.loc[['China', 'Thailand']][['Bronze', 'Continent']]

          Bronze Continent
China          8      Asia
Thailand      12      Asia

As `.loc` only support actual row and column label, we have to select them by it's name, and do chain indexing just like 2.1

### 2.3 Get the intersection of the last two rows and the last two columns **with at least one** `iloc`.

In [15]:
df.iloc[-2:, -2:]

          Bronze Continent
China          8      Asia
Thailand      12      Asia

Access the last two rows and last two columns by index slicing, as `.iloc` is intended to be used.