<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/Copy_of_06_tidy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

*K. Bunchongchit<br>
Last updated on October 7, 2026*

## Outline
1. Tidy Data
2. Data transformation *(continued in the next notebook)*

## Introduction

Why should we tidy up our data?

- 80/20
  - 80% Data preparation
  - 20% Data analysis/data analytics/ML

<img src="https://www.informatica.com/content/dam/informatica-com/en/images/misc/what-is-data-preparation_v1.png" width=50%>

### 1 Tidy Data

#### 1.1 What is tidy data?

Hadley Wickham proposed the term **TIDY DATA**.

>A huge amount of effort is spent cleaning data to get it ready for analysis, but there
has been little research on how to make data cleaning as easy and effective as possible.
This paper tackles a small, but important, component of data cleaning: data tidying.
Tidy datasets are easy to manipulate, model and visualise, and have a specific structure:
each variable is a column, each observation is a row, and each type of observational unit
is a table. This framework makes it easy to tidy messy datasets because only a small
set of tools are needed to deal with a wide range of un-tidy datasets. This structure
also makes it easier to develop tidy tools for data analysis, tools that both input and
output tidy datasets. The advantages of a consistent data structure and matching tools
are demonstrated with a case study free from mundane data manipulation chores. <br>-- Hadley Wickham https://www.jstatsoft.org/article/view/v059i10

The rules for data to be in this form are:

1. Each variable must have its own column.
2. Each observation must have its own row.
3. Each value must have its own cell.

![https://r4ds.had.co.nz/tidy-data.html](https://d33wubrfki0l68.cloudfront.net/6f1ddb544fc5c69a2478e444ab8112fb0eea23f8/91adc/images/tidy-1.png)

#### Prompt 6.1: What is an observation in a research study?

#### Prompt 6.2: Which dataset is tidy?

<table border="1">
    <tbody>
        <tr>
            <td><img src="https://i.ibb.co/9wMF8fr/datasetA.png"></td>
            <td><img src="https://i.ibb.co/RDC3V34/datasetB.png"></td>
            <td><img src="https://i.ibb.co/fdwvBjR/datasetC.png"></td>
        </tr>
        <tr>
            <td style="text-align: center">(a)</td>
            <td style="text-align: center">(b)</td>
            <td style="text-align: center">(c)</td>
        </tr>
    </tbody>
</table>

#### Wide VS Long Data

<a href="https://www.statology.org/wp-content/uploads/2021/12/wideLong1-1.png"><img src="https://www.statology.org/wp-content/uploads/2021/12/wideLong1-1-768x543.png" width=60%></a>

- Wide data is often easier for people to read (e.g., one row per subject in a report).
- Long data is usually easier for tools to group, filter, model, and visualize.
- Whether a table is "tidy" depends on what you treat as a variable and an observation.

#### Tidy Data VS Database Normalization
Similarity: A consistent way to organize data<br>
Difference: Performance of accessing and processing data VS efficiency of storage

#### 1.2 Why tidy data?

**Efficiency that comes with consistently-designed data structures**
- We use data to discover answers to the research problem.
- A research problem naturally has many research questions.
  - Sometimes, we don't even have exact research questions to begin with (*Exploratory Research*).
- Many research questions lead to many hypotheses.
- Data will be prepped and transformed to answer each hypothesis.

> Happy families are all alike; every unhappy family is unhappy in its own way.
<br>*Leo Tolstoy*

#### 1.3 Types of Variables in Research
<a href="https://www.bachelorprint.eu/methodology/types-of-variables-in-research/"><img src="https://drive.google.com/uc?export=view&id=1oURZuae1yYWEeRKslDuDzydHnaTT4XlN" width=70%></a>

### Prompt 6.3: Variables in Research

> **A note on terms used in this notebook.** In research design, *independent* and *dependent* variables describe cause and effect. When tidying, Wickham uses a different pair: **fixed (identifier) variables**, which describe the experimental design and identify each observation (e.g., `religion`, `year`), and **measured variables**, which record what was observed (e.g., a count). The two pairs often line up, but not always.

#### 1.4 Five Most Common Types of Untidy Data
Ref: https://www.jstatsoft.org/article/view/v059i10
1. Column headers are values, not variable names.
2. Multiple variables are stored in one column.
3. Variables are stored in both rows and columns.
4. Multiple types of observational units are stored in the same table.
5. A single observational unit is stored in multiple tables.

##### 1.4.1 Column headers are values, not variable names

The first ten rows of data on income and religion in the US from the Pew Forum. (If you need more details of this research, see http://pewrsr.ch/2dYeCfx. However, it may be a different dataset on that resource, but the nature of the dataset should be the same.)

In [1]:
# pandas is the main library for working with tables (DataFrames) in Python.
# By convention it is imported under the short name "pd".
import pandas as pd

# Base address for downloading a file that is shared publicly on Google Drive.
# Adding a file ID to the end gives a direct download link, e.g. CSV_URL + '<file id>'.
CSV_URL = 'https://drive.google.com/uc?export=download&id='  # For later use

1. Load the dataset.<br>
   Oh ... is this data file in CSV?<br><br>Note that here we are using a data file on the Web rather than on a Google Drive.

In [2]:
# read_csv can read directly from a URL as well as from a local file path.
# Source: https://github.com/chendaniely/pydatadc_2018-tidy/tree/master/data
df_rel = pd.read_csv('https://raw.githubusercontent.com/chendaniely/pydatadc_2018-tidy/master/data/pew.csv')

# Putting a variable name on the last line of a cell displays it as a table.
df_rel

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116
5,Evangelical Prot,575,869,1064,982,881,1486,949,723,414,1529
6,Hindu,1,9,7,9,11,34,47,48,54,37
7,Historically Black Prot,228,244,236,238,197,223,131,81,78,339
8,Jehovah's Witness,20,27,24,24,21,30,15,11,6,37
9,Jewish,19,19,25,25,30,95,69,87,151,162
10,Mainline Prot,289,495,619,655,651,1107,939,753,634,1328
11,Mormon,29,40,48,51,56,112,85,49,42,69
12,Muslim,6,7,9,10,9,23,16,8,6,22
13,Orthodox,13,17,23,32,32,47,38,42,46,73
14,Other Christian,9,7,11,13,13,14,18,14,12,18
15,Other Faiths,20,33,40,46,49,63,46,40,41,71
16,Other World Religions,5,2,3,4,2,7,3,4,4,8
17,Unaffiliated,217,299,374,365,341,528,407,321,258,597

Before we transform the data, we need to know the purpose of this dataset. Many times datasets do not come with descriptions. So we need to establish a basic understanding of the observations that resulted in this dataset.

#### Prompt 6.4: Inferring connections or relationships between different things we see or hear (aka "educated guess")
<sup><sub>(If you are curious about why it is good for your brain, check out [Scientists Discover What Happens in Our Brains When We Make an 'Educated Guess'](https://www.sciencealert.com/scientists-figure-out-what-happens-in-the-brain-when-we-make-educated-guesses))</sub></sup>

2. Get information on this dataset.

In [3]:
# info() lists every column with its data type and how many values are non-missing.
# Look at the column NAMES: are they variable names, or values of some variable?
df_rel.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   religion            18 non-null     str
 1   <$10k               18 non-null     int64
 2   $10-20k             18 non-null     int64
 3   $20-30k             18 non-null     int64
 4   $30-40k             18 non-null     int64
 5   $40-50k             18 non-null     int64
 6   $50-75k             18 non-null     int64
 7   $75-100k            18 non-null     int64
 8   $100-150k           18 non-null     int64
 9   >150k               18 non-null     int64
 10  Don't know/refused  18 non-null     int64
dtypes: int64(10), str(1)
memory usage: 1.7 KB

How to fix this: **Melting** (wide → long).

3. Melt and rename column labels. Ref: https://pandas.pydata.org/docs/reference/api/pandas.melt.html<br>Let's test it on a small subset first.

In [4]:
# pd.melt turns selected COLUMNS into ROWS.
# Each melted column name becomes a value in a new column (var_name),
# and the numbers that were under it go into another new column (value_name).
test = pd.melt(df_rel,                           # the wide DataFrame to reshape
               id_vars=['religion'],             # identifier column(s): kept as they are and repeated on every new row
               value_vars=['<$10k', '$10-20k'],  # only these two columns are melted (a small test)
               var_name='income',                # new column that holds the old column NAMES
               value_name='frequency'            # new column that holds the old cell VALUES (counts)
               )

# Result: 18 religions x 2 income groups = 36 rows.
test

                   religion   income  frequency
0                  Agnostic    <$10k         27
1                   Atheist    <$10k         12
2                  Buddhist    <$10k         27
3                  Catholic    <$10k        418
4        Don’t know/refused    <$10k         15
5          Evangelical Prot    <$10k        575
6                     Hindu    <$10k          1
7   Historically Black Prot    <$10k        228
8         Jehovah's Witness    <$10k         20
9                    Jewish    <$10k         19
10            Mainline Prot    <$10k        289
11                   Mormon    <$10k         29
12                   Muslim    <$10k          6
13                 Orthodox    <$10k         13
14          Other Christian    <$10k          9
15             Other Faiths    <$10k         20
16    Other World Religions    <$10k          5
17             Unaffiliated    <$10k        217
18                 Agnostic  $10-20k         34
19                  Atheist  $10-20k         27
20                 Buddhist  $10-20k         21
21                 Catholic  $10-20k        617
22       Don’t know/refused  $10-20k         14
23         Evangelical Prot  $10-20k        869
24                    Hindu  $10-20k          9
25  Historically Black Prot  $10-20k        244
26        Jehovah's Witness  $10-20k         27
27                   Jewish  $10-20k         19
28            Mainline Prot  $10-20k        495
29                   Mormon  $10-20k         40
30                   Muslim  $10-20k          7
31                 Orthodox  $10-20k         17
32          Other Christian  $10-20k          7
33             Other Faiths  $10-20k         33
34    Other World Religions  $10-20k          2
35             Unaffiliated  $10-20k        299

Now apply the command to the whole dataframe.

In [5]:
df_rel_t = pd.melt(df_rel,
                   id_vars=['religion'],
                   # Melt every column except the first one ('religion').
                   value_vars=list(df_rel.columns)[1:],
                   var_name='income',
                   value_name='frequency'
                   )

# Result: 18 religions x 10 income groups = 180 rows, 3 columns.
df_rel_t

                  religion              income  frequency
0                 Agnostic               <$10k         27
1                  Atheist               <$10k         12
2                 Buddhist               <$10k         27
3                 Catholic               <$10k        418
4       Don’t know/refused               <$10k         15
..                     ...                 ...        ...
175               Orthodox  Don't know/refused         73
176        Other Christian  Don't know/refused         18
177           Other Faiths  Don't know/refused         71
178  Other World Religions  Don't know/refused          8
179           Unaffiliated  Don't know/refused        597

[180 rows x 3 columns]

In [6]:
# Check the new shape: 180 rows and 3 columns (religion, income, frequency).
df_rel_t.info()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   religion   180 non-null    str
 1   income     180 non-null    str
 2   frequency  180 non-null    int64
dtypes: int64(1), str(2)
memory usage: 4.3 KB

#### Practice Problem: Prompt 6.5

Tidy up the [**Billboard dataset**](https://drive.google.com/drive/folders/1LnZzGtnhC2Njc2V_9nn-2-f6WoCbgrYd?usp=sharing) to match the structure shown in the table below. Add as many cells as you need to finish the task.<br>Sure, you can find a solution on the Web, but as a CS major, I'm sure you realize the importance of coming up with an answer of your own (with help on syntax and semantics of certain code pieces from a search engine, of course!)

**Target structure (the first 12 rows of the tidy table):**

| year | artist | track | time | date | week | rank |
|---:|:---|:---|:---|:---|---:|---:|
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-02-26 | 1 | 87 |
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-03-04 | 2 | 82 |
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-03-11 | 3 | 72 |
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-03-18 | 4 | 77 |
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-03-25 | 5 | 87 |
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-04-01 | 6 | 94 |
| 2000 | 2 Pac | Baby Don't Cry (Keep Ya Head Up II) | 4:22 | 2000-04-08 | 7 | 99 |
| 2000 | 2Ge+her | The Hardest Part Of Breaking Up (Is Getting Back Your Stuff) | 3:15 | 2000-09-02 | 1 | 91 |
| 2000 | 2Ge+her | The Hardest Part Of Breaking Up (Is Getting Back Your Stuff) | 3:15 | 2000-09-09 | 2 | 87 |
| 2000 | 2Ge+her | The Hardest Part Of Breaking Up (Is Getting Back Your Stuff) | 3:15 | 2000-09-16 | 3 | 92 |
| 2000 | 3 Doors Down | Kryptonite | 3:53 | 2000-04-08 | 1 | 81 |
| 2000 | 3 Doors Down | Kryptonite | 3:53 | 2000-04-15 | 2 | 70 |

Things to notice in the target:
- One row per song per week on the chart. Weeks when a song was not on the chart do not appear.
- `week` is a number (1, 2, 3, ...), not the original column name such as `x1st.week`.
- `date` is the date of that week's chart: the date the song entered, plus 7 days for each week after the first.
- The rows are sorted by artist, track, and week.

**Self-check:** your finished table should have **5,307 rows** and **7 columns**.

The following code is for Google Colab only. If you use a desktop IDE, just skip the cell below.

If you are using a desktop IDE, try
<pre>df_bill = pd.read_csv('data/billboard.csv')</pre>with the adjusted folder path.

> Note that the file has more columns than the target table (for example `genre` and `date.peaked`), and the artist column is called `artist.inverted`. Deciding what to keep is part of the task.

In [7]:
# Download the Billboard file from Google Drive using its file ID.
df_bill = pd.read_csv(CSV_URL + '1fLZYwrh7bviX9PH0NqTzg6gUqXicucc-')
df_bill

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Inspect column names and types before deciding what to melt.
df_bill.info()

<class 'pandas.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             317 non-null    int64
 1   artist.inverted  317 non-null    str
 2   track            317 non-null    str
 3   time             317 non-null    str
 4   genre            317 non-null    str
 5   date.entered     317 non-null    str
 6   date.peaked      317 non-null    str
 7   x1st.week        317 non-null    int64
 8   x2nd.week        312 non-null    float64
 9   x3rd.week        307 non-null    float64
 10  x4th.week        300 non-null    float64
 11  x5th.week        292 non-null    float64
 12  x6th.week        280 non-null    float64
 13  x7th.week        269 non-null    float64
 14  x8th.week        260 non-null    float64
 15  x9th.week        253 non-null    float64
 16  x10th.week       244 non-null    float64
 17  x11th.week       236 non-null    float64
 18  x12th.week       222 non-null    float64
 19  x13th.week       210 non-null    float64
 20  x14th.week       204 non-null    float64
 21  x15th.week       197 non-null    float64
 22  x16th.week       182 non-null    float64
 23  x17th.week       177 non-null    float64
 24  x18th.week       166 non-null    float64
 25  x19th.week       156 non-null    float64
 26  x20th.week       146 non-null    float64
 27  x21st.week       65 non-null     float64
 28  x22nd.week       55 non-null     float64
 29  x23rd.week       48 non-null     float64
 30  x24th.week       46 non-null     float64
 31  x25th.week       38 non-null     float64
 32  x26th.week       36 non-null     float64
 33  x27th.week       29 non-null     float64
 34  x28th.week       24 non-null     float64
 35  x29th.week       20 non-null     float64
 36  x30th.week       20 non-null     float64
 37  x31st.week       19 non-null     float64
 38  x32nd.week       18 non-null     float64
 39  x33rd.week       12 non-null     float64
 40  x34th.week       10 non-null     float64
 41  x35th.week       9 non-null      float64
 42  x36th.week       9 non-null      float64
 43  x37th.week       9 non-null      float64
 44  x38th.week       8 non-null      float64
 45  x39th.week       8 non-null      float64
 46  x40th.week       7 non-null      float64
 47  x41st.week       7 non-null      float64
 48  x42nd.week       6 non-null      float64
 49  x43rd.week       6 non-null      float64
 50  x44th.week       6 non-null      float64
 51  x45th.week       5 non-null      float64
 52  x46th.week       5 non-null      float64
 53  x47th.week       5 non-null      float64
 54  x48th.week       4 non-null      float64
 55  x49th.week       4 non-null      float64
 56  x50th.week       4 non-null      float64
 57  x51st.week       4 non-null      float64
 58  x52nd.week       4 non-null      float64
 59  x53rd.week       4 non-null      float64
 60  x54th.week       2 non-null      float64
 61  x55th.week       2 non-null      float64
 62  x56th.week       2 non-null      float64
 63  x57th.week       2 non-null      float64
 64  x58th.week       2 non-null      float64
 65  x59th.week       2 non-null      float64
 66  x60th.week       2 non-null      float64
 67  x61st.week       2 non-null      float64
 68  x62nd.week       2 non-null      float64
 69  x63rd.week       2 non-null      float64
 70  x64th.week       2 non-null      float64
 71  x65th.week       1 non-null      float64
 72  x66th.week       0 non-null      float64
 73  x67th.week       0 non-null      float64
 74  x68th.week       0 non-null      float64
 75  x69th.week       0 non-null      float64
 76  x70th.week       0 non-null      float64
 77  x71st.week       0 non-null      float64
 78  x72nd.week       0 non-null      float64
 79  x73rd.week       0 non-null      float64
 80  x74th.week       0 non-null      float64
 81  x75th.week       0 non-null      float64
 82  x76th.week       0 non-null      float64
dtypes: float64(75), int64(2), str(6)
memory usage: 205.7 KB

1. Identify which data to keep.
2. Identify the identifier (fixed) variables and the measured variable.
3. **Write your code in the cell below.** Add more text and code cells as needed.

In [9]:
# Your code here

# Keep song details and turn the weekly columns into rows.
df_bill_tidy = df_bill.melt(
    id_vars=['year', 'artist.inverted', 'track', 'time', 'date.entered'],
    value_vars=df_bill.filter(regex=r'^x\d+.*\.week$').columns,
    var_name='week',
    value_name='rank'
)

# Keep only weeks when the song was on the chart.
df_bill_tidy = df_bill_tidy.dropna(subset=['rank'])

# Extract the number from labels such as 'x1st.week'.
df_bill_tidy['week'] = (
    df_bill_tidy['week'].str.extract(r'(\d+)', expand=False).astype(int)
)

# Week 1 is the entry date; each subsequent week adds 7 days.
df_bill_tidy['date'] = (
    pd.to_datetime(df_bill_tidy['date.entered'])
    + pd.to_timedelta((df_bill_tidy['week'] - 1) * 7, unit='D')
)

df_bill_tidy = df_bill_tidy.rename(columns={'artist.inverted': 'artist'})
df_bill_tidy['rank'] = df_bill_tidy['rank'].astype(int)

# Match the requested columns and ordering.
df_bill_tidy = (
    df_bill_tidy[['year', 'artist', 'track', 'time', 'date', 'week', 'rank']]
    .sort_values(['artist', 'track', 'week'])
    .reset_index(drop=True)
)

display(df_bill_tidy)
print(df_bill_tidy.shape)  # Expected: (5307, 7)

,year,artist,track,time,date,week,rank
0,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,2000-02-26,1,87
1,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,2000-03-04,2,82
2,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,2000-03-11,3,72
3,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,2000-03-18,4,77
4,2000,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,2000-03-25,5,87
...,...,...,...,...,...,...,...
5302,2000,matchbox twenty,Bent,4:12,2000-12-23,35,33
5303,2000,matchbox twenty,Bent,4:12,2000-12-30,36,37
5304,2000,matchbox twenty,Bent,4:12,2001-01-06,37,38
5305,2000,matchbox twenty,Bent,4:12,2001-01-13,38,38
5306,2000,matchbox twenty,Bent,4:12,2001-01-20,39,48

(5307, 7)

##### 1.4.2 Multiple variables stored in one column

Let's look at a [tuberculosis (TB)](https://git.scicore.unibas.ch/dokmanic-courses/pids26/-/blob/main/Lecture/data/tb-all.csv?ref_type=heads) dataset. Columns starting with 'm' are for males and those starting with
'f' are for females. The digits after the letter indicate the age range.

If you are using a desktop IDE, try
<pre>df_tb = pd.read_csv('data/tb.csv')</pre>with the adjusted folder path.

In [10]:
# Download the TB file from Google Drive using its file ID.
df_tb = pd.read_csv(CSV_URL + '1edMF7cm7WEn5SVkvznbfPFTiQK7OdOnt')
df_tb

,iso2,year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
0,AD,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AD,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AD,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD,1993,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5764,ZW,2004,14581.0,NaN,NaN,187.0,833.0,2908.0,2298.0,1056.0,...,NaN,NaN,225.0,1140.0,2858.0,1565.0,622.0,214.0,111.0,NaN
5765,ZW,2005,13155.0,NaN,NaN,210.0,837.0,2264.0,1855.0,762.0,...,NaN,NaN,269.0,1136.0,2242.0,1255.0,578.0,193.0,603.0,NaN
5766,ZW,2006,12718.0,NaN,NaN,215.0,736.0,2391.0,1939.0,896.0,...,NaN,NaN,237.0,1020.0,2424.0,1355.0,632.0,230.0,96.0,NaN
5767,ZW,2007,10583.0,6.0,132.0,138.0,500.0,3693.0,0.0,716.0,...,7.0,178.0,185.0,739.0,3311.0,0.0,553.0,213.0,90.0,NaN
5768,ZW,2008,9830.0,NaN,NaN,127.0,614.0,0.0,3316.0,704.0,...,NaN,NaN,145.0,840.0,0.0,2890.0,467.0,174.0,105.0,0.0

In [11]:
# Note: 23 columns. 'iso2' (country) and 'year' identify a row;
# 'new_sp' is a TOTAL; the other 20 columns each mix sex AND age in their names.
df_tb.info()

<class 'pandas.DataFrame'>
RangeIndex: 5769 entries, 0 to 5768
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   iso2          5746 non-null   str
 1   year          5769 non-null   int64
 2   new_sp        3081 non-null   float64
 3   new_sp_m04    392 non-null    float64
 4   new_sp_m514   401 non-null    float64
 5   new_sp_m014   2381 non-null   float64
 6   new_sp_m1524  2407 non-null   float64
 7   new_sp_m2534  2408 non-null   float64
 8   new_sp_m3544  2415 non-null   float64
 9   new_sp_m4554  2421 non-null   float64
 10  new_sp_m5564  2414 non-null   float64
 11  new_sp_m65    2408 non-null   float64
 12  new_sp_mu     273 non-null    float64
 13  new_sp_f04    393 non-null    float64
 14  new_sp_f514   404 non-null    float64
 15  new_sp_f014   2378 non-null   float64
 16  new_sp_f1524  2394 non-null   float64
 17  new_sp_f2534  2400 non-null   float64
 18  new_sp_f3544  2398 non-null   float64
 19  new_sp_f4554  2401 non-null   float64
 20  new_sp_f5564  2394 non-null   float64
 21  new_sp_f65    2396 non-null   float64
 22  new_sp_fu     272 non-null    float64
dtypes: float64(21), int64(1), str(1)
memory usage: 1.0 MB

### Prompt 6.6: What is the nature of this TB data set?

Complete the assigned task on Canvas.

Now let's dive into coding.<br>Ref: https://www.jeannicholashould.com/tidy-data-in-python.html

A. Drop the total column, then melt.

The column `new_sp` is the **total** of all the other columns, so it is a different kind of observation (an aggregate). If we keep it, a row labelled "total" would sit next to the rows it summarizes, and any later sum would count the same cases twice.

In [12]:
# Remove the aggregate column before reshaping.
# errors='ignore' means: do nothing (instead of failing) if the column is already gone.
df_tb_detail = df_tb.drop(columns=['new_sp'], errors='ignore')

# Melt the 20 sex-and-age columns into rows.
df_tb_m = pd.melt(df_tb_detail,
                  id_vars=["iso2", "year"],    # identifiers kept on every row
                  value_name="cases",          # the numbers go here
                  var_name="sex_and_age"       # the old column names (e.g. 'new_sp_m014') go here
                  )

# info() prints its report directly, so it does not need display().
df_tb_m.info()
df_tb_m

<class 'pandas.DataFrame'>
RangeIndex: 115380 entries, 0 to 115379
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   iso2         114920 non-null  str
 1   year         115380 non-null  int64
 2   sex_and_age  115380 non-null  str
 3   cases        35750 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 3.5 MB

       iso2  year sex_and_age  cases
0        AD  1989  new_sp_m04    NaN
1        AD  1990  new_sp_m04    NaN
2        AD  1991  new_sp_m04    NaN
3        AD  1992  new_sp_m04    NaN
4        AD  1993  new_sp_m04    NaN
...     ...   ...         ...    ...
115375   ZW  2004   new_sp_fu    NaN
115376   ZW  2005   new_sp_fu    NaN
115377   ZW  2006   new_sp_fu    NaN
115378   ZW  2007   new_sp_fu    NaN
115379   ZW  2008   new_sp_fu    0.0

[115380 rows x 4 columns]

In [13]:
# sample(10) shows 10 random rows; useful for spot-checking a large table.
df_tb_m.sample(10)

       iso2  year   sex_and_age  cases
100308   HU  1994  new_sp_f5564    NaN
49659    MT  1999    new_sp_m65    3.0
21283    NZ  1992  new_sp_m1524    NaN
90518    NZ  1999  new_sp_f3544    2.0
96547    PR  2000  new_sp_f4554    7.0
65371    GM  1996   new_sp_f514    NaN
16381    ST  2001   new_sp_m014    0.0
99349    CY  1990  new_sp_f5564    NaN
47884    FM  2003    new_sp_m65    1.0
44346    NU  2008  new_sp_m5564    NaN

B. Split the <code>sex_and_age</code> column into two variables: sex and age.<br>If you would like to know more about regular expressions, check out [How to write Regular Expressions?](https://www.geeksforgeeks.org/write-regular-expressions/)

The codes after `new_sp_` follow this pattern: one letter for sex, then an age code.

| Age code | Meaning |
|---|---|
| `04` | 0-4 |
| `514` | 5-14 |
| `014` | 0-14 |
| `1524`, `2534`, ..., `5564` | 15-24, 25-34, ..., 55-64 |
| `65` | 65 and over |
| `u` | unknown |

Because the age codes have different lengths (2, 3, or 4 characters), the digits cannot be split by position alone. We first *extract* the sex letter and the age code with a regular expression, then translate each age code with a lookup table.

In [14]:
import numpy as np

# Regular expression, piece by piece:
#   ^new_sp_      the text must start with 'new_sp_'
#   (?P<sex>[mf]) capture one letter, m or f, and call the group 'sex'
#   (?P<age_code>\d+|u)  capture either one or more digits, or the letter u, as 'age_code'
#   $             nothing may follow (so no partial matches)
pattern = r'^new_sp_(?P<sex>[mf])(?P<age_code>\d+|u)$'

# str.extract applies the pattern to every row and returns one column per named group.
tmp_df = df_tb_m['sex_and_age'].str.extract(pattern)

# Lookup table: age code -> readable age range.
AGE_LABELS = {
    '04': '0-4',
    '514': '5-14',
    '014': '0-14',
    '1524': '15-24',
    '2534': '25-34',
    '3544': '35-44',
    '4554': '45-54',
    '5564': '55-64',
    '65': '65+',
    'u': 'unknown',
}

# map() replaces each code with its label; any code not in the table becomes NaN.
tmp_df['age'] = tmp_df['age_code'].map(AGE_LABELS)

# Safety check: stop with an error if any column name did not match the pattern
# or used an age code we did not expect. Silent NaNs are how parsing bugs hide.
unmatched = df_tb_m.loc[tmp_df['age'].isna(), 'sex_and_age'].unique()
assert len(unmatched) == 0, f"Unexpected column codes: {unmatched}"

display(tmp_df.sample(10))

       sex age_code      age
77997    f     1524    15-24
33798    m     3544    35-44
71538    f      014     0-14
55516    m        u  unknown
32209    m     3544    35-44
64723    f      514     5-14
99349    f     5564    55-64
54416    m        u  unknown
113472   f        u  unknown
70917    f      014     0-14

C. Add the new columns to the melted table and drop the old combined column.

In [15]:
# Copy the parsed columns into df_tb_m.
# Both tables share the same row index, so pandas lines up the rows automatically.
df_tb_m['sex'] = tmp_df['sex']
df_tb_m['age'] = tmp_df['age']

# 'sex_and_age' is now redundant: its information lives in 'sex' and 'age'.
df_tb_m = df_tb_m.drop(columns=['sex_and_age'])

# Put the columns in a sensible order: identifiers first, measurement last.
df_tb_m = df_tb_m[['iso2', 'year', 'sex', 'age', 'cases']]

df_tb_m

       iso2  year sex      age  cases
0        AD  1989   m      0-4    NaN
1        AD  1990   m      0-4    NaN
2        AD  1991   m      0-4    NaN
3        AD  1992   m      0-4    NaN
4        AD  1993   m      0-4    NaN
...     ...   ...  ..      ...    ...
115375   ZW  2004   f  unknown    NaN
115376   ZW  2005   f  unknown    NaN
115377   ZW  2006   f  unknown    NaN
115378   ZW  2007   f  unknown    NaN
115379   ZW  2008   f  unknown    0.0

[115380 rows x 5 columns]

In [16]:
df_tb_m.sample(10)

       iso2  year sex      age  cases
77748    KR  1985   f    15-24    NaN
33730    SY  1985   m    35-44    NaN
106966   LY  1994   f      65+    NaN
85001    PR  1991   f    25-34    NaN
101149   LU  2003   f    55-64    0.0
114606   TG  1996   f  unknown    NaN
81948    CO  2006   f    25-34  653.0
112986   MN  2002   f  unknown    NaN
89654    LY  1988   f    35-44    NaN
45568    TO  2008   m    55-64    1.0

In [17]:
# Final check: every age label should be one of the ten readable ranges above.
print(df_tb_m['age'].unique())

<StringArray>
[    '0-4',    '5-14',    '0-14',   '15-24',   '25-34',   '35-44',   '45-54',
   '55-64',     '65+', 'unknown']
Length: 10, dtype: str

Finally the TB dataset looks tidy!

> Look closely at the age groups: `0-14` overlaps with `0-4` and `5-14`. Tidy does not mean ready to analyze; adding all age groups together would still double-count some children.

##### 1.4.3 Variables are stored in both rows and columns

In this section, we will go back to the daily weather data from the Global Historical Climatology Network for one weather station (MX17004) in Mexico from 1955 to 2011. Recall that the data set has a column for each possible day in the month, and the "element" column indicates if that row contains the minimum or maximum temperature or the amount of precipitation. Recall there are many problems with this dataset.
- The first data row is turned into the column labels.
- There is only one column of data.
- Letters such as "I" and "S" appear between the numbers. They are not separators: in the GHCN-Daily format each daily value is followed by flag characters (measurement, quality, and source flags).

If you are using a desktop IDE, try
<pre>df_wt = pd.read_csv('data/weather.txt', header=0, sep='\t', engine='python')</pre>with the adjusted folder path.

### Prompt 6.7: What is untidy in the Weather Station data set?
Complete the assigned task on Canvas.

---

Let's load the data file, and quickly clean it like we did before.

In [18]:
import pandas as pd
import numpy as np
import urllib.request   # for downloading a file from a URL
import re               # regular expressions, for pulling numbers out of text


data = []   # will hold one dictionary per line of the file

url = 'https://drive.google.com/uc?export=download&id=1d9b_at4SJMlgtzQ04isPjUVzGEm7hYsl'

# Download the raw file. The 'with' block closes the connection automatically.
with urllib.request.urlopen(url) as f:
    content_bytes = f.read()                      # raw bytes from the web
    text_content = content_bytes.decode('utf-8')  # bytes -> text
    lines = text_content.splitlines()             # text -> list of lines

    # Show the first and last 10 lines so we can see what we are dealing with.
    _ = [print(line) for line in lines[:10]]
    print('...')
    _ = [print(line) for line in lines[-10:]]

    for line in lines:
        if not line.strip():    # skip empty lines
            continue

        # 1. Parse metadata. The first 21 characters have fixed widths:
        #    characters 0-10 station ID | 11-14 year | 15-16 month | 17-20 element (e.g. TMAX)
        station_id = line[:11]
        year = int(line[11:15])
        month = int(line[15:17])
        element = line[17:21]

        # 2. Parse data values (the rest of the line).
        # Pull out every whole number, including -9999 (the "missing" code).
        # Assumption: the flag characters between values are letters or blanks.
        # (True for this file: every line yields exactly 31 numbers.)
        # If a flag were a digit, this would pick up extra numbers and shift the days,
        # so re-check this assumption before reusing the code on another GHCN file.
        raw_data = line[21:]
        daily_values = re.findall(r'-?\d+', raw_data)

        # 3. Store the line as a dictionary: identifiers first...
        row = {
            'ID': station_id,
            'Year': year,
            'Month': month,
            'Element': element
        }

        # ...then one key per day: Day_1, Day_2, ..., Day_31.
        for i, value in enumerate(daily_values):
            row[f'Day_{i+1}'] = value

        data.append(row)

# 4. Create the initial DataFrame: still WIDE (one column per day).
df = pd.DataFrame(data)

MX000017004195504TMAX  310  I  310  I  310  I  320  I  330  I  320  I  320  I  330  I  330  I  330  I  330  I  320  I  310  I  310  I  320  I  320  I  320  I  310  I  310  I  320  I  320  I  330  I  330  I  330  I  330  I  330  I  330  I  340  I  330  I  320  I-9999
MX000017004195504TMIN  150  I  150  I  160  I  150  I  160  I  160  I  160  I  160  I  160  I  170  I  170  I  160  I  160  I  160  I  170  I  170  I  160  I  160  I  160  I  160  I  170  I  170  I  170  I  170  I  180  I  190  I  190  I  170  I  180  I  160  I-9999
MX000017004195504PRCP    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    6  I-9999
MX000017004195505TMAX  310  I  310  I  310  I  300  I  300  I  300  I  310  I  310  I  310  I  300  I  300  I  310  I  300  I  310  I  320  I  320  I  330  I  330  I  330  I  300  I  350  I  330  I  340  I  350  I  330  I  310  I  310  I  320  I  310  I  300  I  290  I
MX000017004195505TMIN  200  I  160  I  160  I  150  I  150  I  150  I  160  I  160  I  170  I  170  I  170  I  170  I  160  I  170  I  170  I  180  I  190  I  180  I  180  I  180  I  200  I  170  I  190  I  190  I  190  I  180  I  160  I  150  I  170  I  150  I  160  I
MX000017004195505PRCP    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I   12  I   24  I    0  I    0  I    0  I    0  I    0  I    0  I    0  I    5  I    0  I    0  I    0  I    0  I    0  I  142  I    0  I   54  I    0  I   46  I
MX000017004195506TMAX  300  I  290  I  280  I  270  I  280  I  260  I  230  I  270  I  280  I  280  I  270  I  290  I  290  I  270  I  290  I  290  I  290  I  300  I  300  I  300  I  300  I  290  I  270  I  270  I  270  I  280  I  300  I  270  I  290  I  270  I-9999
MX000017004195506TMIN  160  I  160  I  150  I  140  I  160  I  150  I  150  I  150  I  160  I  150  I  160  I  180  I  170  I  140  I  160  I  150  I  160  I  170  I  160  I  170  I  170  I  160  I  170  I  150  I  160  I  160  I  160  I  180  I  150  I  150  I-9999
MX000017004195506PRCP  103  I  435  I  422  I    0  I  243  I   17  I    0  I    0  I    0  I   27  I    0  I   15  I  292  I    0  I   28  I   76  I    0  I    0  I    0  I    0  I    0  I    0  I   44  I   52  I    3  I   13  I    0  I   37  I  165  I  323  I-9999
MX000017004195507TMAX  270  I  270  I  260  I  260  I  240  I  240  I  190  I  210  I  250  I  250  I  260  I  240  I  250  I  250  I  270  I  240  I  230  I  240  I  230  I  240  I  240  I  230  I  240  I  240  I  260  I  260  I  260  I  260  I  260  I  260  I  260  I
...
MX000017004201101PRCP    0  S-9999       0  S    0  S    0  S    0  S    0  S    0  S-9999   -9999       0  S    0  S    0  S-9999       0  S-9999   -9999       0  S    0  S    0  S-9999       0  S-9999   -9999       0  S    0  S    0  S    0  S    0  S-9999   -9999
MX000017004201102TMAX-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999     304  S-9999     312  S-9999     316  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999
MX000017004201102TMIN-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999     136  S-9999     134  S-9999     128  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999
MX000017004201102PRCP    0  S    0  S    0  S    0  S    0  S-9999   -9999       0  S    0  S    0  S    0  S    0  S-9999   -9999       0  S-9999       0  S    0  S    0  S-9999   -9999       0  S    0  S    0  S    0  S    0  S-9999   -9999   -9999   -9999   -9999
MX000017004201103TMAX-9999   -9999   -9999   -9999     332  S-9999   -9999   -9999   -9999     320  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999     332  S-9999   -9999   -9999   -9999     365  S
MX000017004201103TMIN-9999   -9999   -9999   -9999     148  S-9999   -9999   -9999   -9999     127  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999     162  S-9999   -9999   -9999   -9999     170  S
MX000017004201103PRCP    0  S-9999       0  S    0  S    0  S-9999       0  S    0  S    0  S    0  S-9999       0  S-9999   -9999       0  S-9999       0  S-9999       0  S-9999   -9999       0  S-9999       0  S-9999       0  S-9999   -9999       0  S-9999       0  S
MX000017004201104TMAX-9999     350  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999
MX000017004201104TMIN-9999     168  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999
MX000017004201104PRCP    0  S    0  S-9999   -9999       0  S    0  S-9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999   -9999

In [19]:
# Look at the wide table BEFORE fixing it: days are spread across 31 columns.
df.head()

,ID,Year,Month,Element,Day_1,Day_2,Day_3,Day_4,Day_5,Day_6,...,Day_22,Day_23,Day_24,Day_25,Day_26,Day_27,Day_28,Day_29,Day_30,Day_31
0,MX000017004,1955,4,TMAX,310,310,310,320,330,320,...,330,330,330,330,330,330,340,330,320,-9999
1,MX000017004,1955,4,TMIN,150,150,160,150,160,160,...,170,170,170,180,190,190,170,180,160,-9999
2,MX000017004,1955,4,PRCP,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,-9999
3,MX000017004,1955,5,TMAX,310,310,310,300,300,300,...,330,340,350,330,310,310,320,310,300,290
4,MX000017004,1955,5,TMIN,200,160,160,150,150,150,...,170,190,190,190,180,160,150,170,150,160

In [20]:
# 5. Transform from wide (Day_1 ... Day_31) to long (one row per day).
# This creates a 'Day_Col' column (old column names) and a 'Value' column (the readings).
id_vars = ['ID', 'Year', 'Month', 'Element']
df_long = df.melt(id_vars=id_vars, var_name='Day_Col', value_name='Value')

# Extract the day number from strings such as 'Day_1', 'Day_2', ... and store it as an integer.
df_long['Day'] = df_long['Day_Col'].str.extract(r'(\d+)', expand=False).astype(int)

# 6. Create the 'Date' column from Year, Month, Day.
# errors='coerce' turns impossible dates (e.g. February 30th) into NaT ("not a time").
df_long['Date'] = pd.to_datetime(
    df_long[['Year', 'Month', 'Day']],
    errors='coerce'
)

# Drop rows whose date is invalid (NaT). Missing readings (-9999) are handled later.
df_long = df_long.dropna(subset=['Date'])

# Store the date as text in yyyy-mm-dd format.
df_long['Date'] = df_long['Date'].dt.strftime('%Y-%m-%d')

# 7. Final cleanup
# Keep only the columns we need, in a readable order.
# Note: TMAX, TMIN and PRCP values are still mixed together in one 'Value' column.
final_df = df_long[['ID', 'Date', 'Element', 'Value']]

# Sort for readability and renumber the rows from 0.
df_wt = final_df.sort_values(by=['ID', 'Date', 'Element']).reset_index(drop=True)

In [21]:
display(df_wt)
display(df_wt.sample(10))

                ID        Date Element  Value
0      MX000017004  1955-04-01    PRCP      0
1      MX000017004  1955-04-01    TMAX    310
2      MX000017004  1955-04-01    TMIN    150
3      MX000017004  1955-04-02    PRCP      0
4      MX000017004  1955-04-02    TMAX    310
...            ...         ...     ...    ...
52186  MX000017004  2011-04-29    TMAX  -9999
52187  MX000017004  2011-04-29    TMIN  -9999
52188  MX000017004  2011-04-30    PRCP  -9999
52189  MX000017004  2011-04-30    TMAX  -9999
52190  MX000017004  2011-04-30    TMIN  -9999

[52191 rows x 4 columns]

                ID        Date Element Value
20921  MX000017004  1975-09-03    PRCP    15
7851   MX000017004  1962-10-30    TMAX   260
51234  MX000017004  2010-05-27    PRCP     0
39490  MX000017004  1998-11-18    PRCP     0
4979   MX000017004  1959-12-15    TMIN   130
20949  MX000017004  1975-09-12    TMAX   230
24397  MX000017004  1978-11-04    TMIN   160
3551   MX000017004  1958-08-26    TMIN   160
8346   MX000017004  1963-05-13    TMAX   200
25983  MX000017004  1980-04-16    TMAX   290

The last two things to do are
- to replace `-9999` with `numpy.nan` (GHCN uses -9999 to mean "missing").
- to convert the units: GHCN stores temperatures in tenths of °C and precipitation in tenths of mm, so we divide by 10.

In [22]:
# The values were read as text; convert them to numbers.
# errors='coerce' turns anything that is not a number into NaN.
df_wt['Value'] = pd.to_numeric(df_wt['Value'], errors='coerce')

# Replace the sentinel value -9999 with NaN, in the 'Value' column only.
df_wt['Value'] = df_wt['Value'].replace(-9999, np.nan)

# Convert tenths to whole units. Dividing a column applies to every row at once,
# and NaN / 10 stays NaN, so no special handling is needed.
df_wt['Value'] = df_wt['Value'] / 10

df_wt

                ID        Date Element  Value
0      MX000017004  1955-04-01    PRCP    0.0
1      MX000017004  1955-04-01    TMAX   31.0
2      MX000017004  1955-04-01    TMIN   15.0
3      MX000017004  1955-04-02    PRCP    0.0
4      MX000017004  1955-04-02    TMAX   31.0
...            ...         ...     ...    ...
52186  MX000017004  2011-04-29    TMAX    NaN
52187  MX000017004  2011-04-29    TMIN    NaN
52188  MX000017004  2011-04-30    PRCP    NaN
52189  MX000017004  2011-04-30    TMAX    NaN
52190  MX000017004  2011-04-30    TMIN    NaN

[52191 rows x 4 columns]

Our work is not done yet. As suggested in the paper, we need one more step to put each observation in its own row: the `Element` column holds variable *names* (TMAX, TMIN, PRCP), so it should be spread into columns.

<img src="https://i.ibb.co/kQHMTB7/final-weather.png" width=60%>

In [23]:
# pivot is the opposite of melt: values in 'Element' become new column names.
# One row per (ID, Date); one column per element.
# pivot raises an error if any (ID, Date, Element) appears twice, which is a useful check.
# (pivot_table would silently average duplicates instead.)
df_wt_pivoted = df_wt.pivot(
    index=['ID', 'Date'],
    columns='Element',
    values='Value'
).reset_index()   # turn ID and Date back into ordinary columns

df_wt_pivoted.columns.name = None   # remove the leftover 'Element' label above the column names

# Display the tidied DataFrame
display(df_wt_pivoted)
display(df_wt_pivoted.sample(10))

                ID        Date  PRCP  TMAX  TMIN
0      MX000017004  1955-04-01   0.0  31.0  15.0
1      MX000017004  1955-04-02   0.0  31.0  15.0
2      MX000017004  1955-04-03   0.0  31.0  16.0
3      MX000017004  1955-04-04   0.0  32.0  15.0
4      MX000017004  1955-04-05   0.0  33.0  16.0
...            ...         ...   ...   ...   ...
17870  MX000017004  2011-04-26   NaN   NaN   NaN
17871  MX000017004  2011-04-27   NaN   NaN   NaN
17872  MX000017004  2011-04-28   NaN   NaN   NaN
17873  MX000017004  2011-04-29   NaN   NaN   NaN
17874  MX000017004  2011-04-30   NaN   NaN   NaN

[17875 rows x 5 columns]

                ID        Date  PRCP  TMAX  TMIN
220    MX000017004  1955-11-07   2.5  24.0  13.0
14592  MX000017004  2002-05-05   0.0  35.4  18.9
17603  MX000017004  2010-08-02   NaN   NaN   NaN
3189   MX000017004  1964-07-24   2.0  25.0  15.0
8122   MX000017004  1978-08-25   8.5  26.0  16.0
2241   MX000017004  1961-07-19   1.6  27.0  17.0
4150   MX000017004  1967-06-09  15.6  28.8  19.1
14250  MX000017004  2001-05-28   0.0   NaN   NaN
8743   MX000017004  1980-05-07   0.0  29.5  16.0
4649   MX000017004  1968-10-20   0.0  26.4  15.2

#### 1.4.4 Multiple types in one table

Let's revisit the Billboard dataset. Even after tidying up, there are still a lot of repetitions in the dataset. This is due to multiple types of observations in one data set.

<img src="https://i.ibb.co/1Zb4sPS/tidy-billboard.png" width=60%>

### Prompt 6.8 on Canvas

#### 1.4.5 One type in multiple tables
- Data values about a single type of observational unit spread out over multiple tables or files
- For example, store the weather data into three files--`min_temp.csv`, `max_temp.csv`, and `prcp.csv`.
- How to fix this: merge datasets

First, let's create the problem on purpose by splitting our tidy weather table into three.

In [24]:
# Each table keeps the identifiers (ID, Date) plus ONE measured variable.
df_min_temp = df_wt_pivoted[['ID', 'Date', 'TMIN']]
df_max_temp = df_wt_pivoted[['ID', 'Date', 'TMAX']]
df_prcp = df_wt_pivoted[['ID', 'Date', 'PRCP']]

print("df_min_temp head:")
display(df_min_temp.head())
print("\ndf_max_temp head:")
display(df_max_temp.head())
print("\ndf_prcp head:")
display(df_prcp.head())

df_min_temp head:

            ID        Date  TMIN
0  MX000017004  1955-04-01  15.0
1  MX000017004  1955-04-02  15.0
2  MX000017004  1955-04-03  16.0
3  MX000017004  1955-04-04  15.0
4  MX000017004  1955-04-05  16.0

df_max_temp head:

            ID        Date  TMAX
0  MX000017004  1955-04-01  31.0
1  MX000017004  1955-04-02  31.0
2  MX000017004  1955-04-03  31.0
3  MX000017004  1955-04-04  32.0
4  MX000017004  1955-04-05  33.0

df_prcp head:

            ID        Date  PRCP
0  MX000017004  1955-04-01   0.0
1  MX000017004  1955-04-02   0.0
2  MX000017004  1955-04-03   0.0
3  MX000017004  1955-04-04   0.0
4  MX000017004  1955-04-05   0.0

Now fix it by merging the tables back together on the columns they share.

In [25]:
# merge joins two tables row by row wherever the key columns match.
# on=['ID', 'Date']   : the columns that identify the same observation in both tables
# how='outer'         : keep a date even if it appears in only one table
# validate='one_to_one': stop with an error if a key appears more than once in either table
df_merged = (df_min_temp
             .merge(df_max_temp, on=['ID', 'Date'], how='outer', validate='one_to_one')
             .merge(df_prcp,     on=['ID', 'Date'], how='outer', validate='one_to_one'))

# Check: the merged table should have the same shape as the table we started from.
print(df_merged.shape, df_wt_pivoted.shape)
df_merged.head()

(17875, 5) (17875, 5)

            ID        Date  TMIN  TMAX  PRCP
0  MX000017004  1955-04-01  15.0  31.0   0.0
1  MX000017004  1955-04-02  15.0  31.0   0.0
2  MX000017004  1955-04-03  16.0  31.0   0.0
3  MX000017004  1955-04-04  15.0  32.0   0.0
4  MX000017004  1955-04-05  16.0  33.0   0.0

#### References
- [R for Data Science (Book)](https://r4ds.had.co.nz/index.html)
- [What Is Data Preparation?](https://www.informatica.com/tw/resources/articles/what-is-data-preparation.html)
- [Tidy Data](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html)
- [Tidy Data (Paper)](https://www.jstatsoft.org/article/view/v059i10)
- [Thoughts on Teaching R and Yet Another Tidyverse Intro](https://www.r-bloggers.com/2018/03/thoughts-on-teaching-r-and-yet-another-tidyverse-intro/) (images)