<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/Copy_of_05_DataManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation

*Originally from <code>pandas</code>'s [Merge, join, concatenate and compare](https://pandas.pydata.org/docs/user_guide/merging.html)<br>
Modified by B. Mathayomchan and K. Bunchongchit*<br>
Last edited on May 6, 2026

## Introduction

Data that are perfectly structured in one file ready for your data science tasks are extremely rare. In real life, we need to construct data from different sources and files before we can start to explore and understand how these data could be useful to our research question. This notebook lists basic commands in pandas that help us shape our data.

## Basic Data Manipulation Methods
- Combining Data Sets
    - Adding rows from a dataframe with identical columns
    - Adding a dataframe where columns are not identical
    - Adding Columns
    - Adding along the direction of column
- Merging (combining dataframes base on values)
  - One-to-One Merge
  - Many-to-One Merge
  - One-to-Many Merge
  - Many-to-Many Merge
- Joining on keys

### Combining Data Sets

Three common methods:

- `pandas.concat()`: across rows or columns
- `DataFrame.merge()`: on common columns or indices
- `DataFrame.join()`: on a key column or an index

*Reference*
- [Three ways to combine DataFrames in Pandas](https://www.educative.io/answers/three-ways-to-combine-dataframes-in-pandas)

### Adding rows from a dataframe with identical columns

In [1]:
import pandas as pd
import numpy as np

CSV_URL = 'https://drive.google.com/uc?export=download&id='

The following code is for **Google Colab only**.

In [2]:
# Load muic1.csv
df1 = pd.read_csv(CSV_URL + '1W_rGyWriKyYk0yFkwwO_3KNmJWPxwsn1')
# Load muic2.csv
df2 = pd.read_csv(CSV_URL + '1QCbItzfbLDgojZkZwWU6sMi2HZ4c03oD')
# Load muic3.csv
df3 = pd.read_csv(CSV_URL + '1-yHsuPzNn7sBj4FWT58YPcQGZ1yD5no1')

If you use a **desktop IDE**,
1. Download the data files from https://drive.google.com/drive/folders/1all1VgS-0bFr9uB27NWG8UXzrIBTh2Xl?usp=sharing
2. Replace both lines below with your local file paths, such as
```python
df1 = pd.read_csv('./datasets/muic1.csv')
df2 = pd.read_csv('./datasets/muic2.csv')
df3 = pd.read_csv('./datasets/muic3.csv')
```

In [3]:
df1

        ID            Name  Major  GPA
0  6780001      Ann Molive   ICCH  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1

In [4]:
df2

        ID         Name  Major  GPA
0  6780031      Tom Lee   ICCS  2.7
1  6780032     Pat Cade   ICFS  3.8
2  6780033   Will Power   ICBA  2.7
3  6780034   Arty Didas   ICFS  3.2
4  6780035    Bart Yolo   ICCS  1.7

In [5]:
df3

        ID               Name  Major  GPA
0  6780021         Terry Cuda   ICCS  1.9
1  6780022        Justin Bull   ICBA  2.8
2  6780023       Ed Cheerbeer   ICCS  4.0
3  6780024          Luke Warm   ICCS  1.2
4  6780025   Anakin Skywalker   ICJD  NaN

In [6]:
row_concat1 = pd.concat([df1, df2, df3])
row_concat1.shape

(15, 4)

In [7]:
row_concat1

        ID               Name  Major  GPA
0  6780001         Ann Molive   ICCH  3.2
1  6780002         Ben Kenobi   ICJD  NaN
2  6780003      Peter Cruiser   ICBA  3.3
3  6780004         Bob Hanger   ICFS  3.5
4  6780005           Moe Otto   ICCS  3.1
0  6780031            Tom Lee   ICCS  2.7
1  6780032           Pat Cade   ICFS  3.8
2  6780033         Will Power   ICBA  2.7
3  6780034         Arty Didas   ICFS  3.2
4  6780035          Bart Yolo   ICCS  1.7
0  6780021         Terry Cuda   ICCS  1.9
1  6780022        Justin Bull   ICBA  2.8
2  6780023       Ed Cheerbeer   ICCS  4.0
3  6780024          Luke Warm   ICCS  1.2
4  6780025   Anakin Skywalker   ICJD  NaN

Notice the order of cancatenation as indicated in the image below.

<img src="https://drive.google.com/uc?export=view&id=1xy_hOqFhjBUckEqN3wP9qdCX_Fyz-fYn" width="40%">

Subset the 4<sup>th</sup> student out, notice that there are many rows in index 3 since they all match the label.

In [8]:
row_concat1.loc[3]

        ID         Name  Major  GPA
3  6780004   Bob Hanger   ICFS  3.5
3  6780034   Arty Didas   ICFS  3.2
3  6780024    Luke Warm   ICCS  1.2

To get the only the 4th row, we use `iloc`. `iloc` is the integer location, so only one row will be returned.

In [9]:
row_concat1.iloc[3]

ID           6780004
Name      Bob Hanger
Major           ICFS
GPA              3.5
Name: 3, dtype: object

Doing it this way will have a confusing index. So, we may want to ignore the original index.

In [10]:
row_concat2 = pd.concat([df1, df2, df3], ignore_index=True)
row_concat2  # notice the nicely running index below

         ID               Name  Major  GPA
0   6780001         Ann Molive   ICCH  3.2
1   6780002         Ben Kenobi   ICJD  NaN
2   6780003      Peter Cruiser   ICBA  3.3
3   6780004         Bob Hanger   ICFS  3.5
4   6780005           Moe Otto   ICCS  3.1
5   6780031            Tom Lee   ICCS  2.7
6   6780032           Pat Cade   ICFS  3.8
7   6780033         Will Power   ICBA  2.7
8   6780034         Arty Didas   ICFS  3.2
9   6780035          Bart Yolo   ICCS  1.7
10  6780021         Terry Cuda   ICCS  1.9
11  6780022        Justin Bull   ICBA  2.8
12  6780023       Ed Cheerbeer   ICCS  4.0
13  6780024          Luke Warm   ICCS  1.2
14  6780025   Anakin Skywalker   ICJD  NaN

### Adding a dataframe where columns are not identical
#### Case I : A subset

Recall `df1`.

In [11]:
df1

        ID            Name  Major  GPA
0  6780001      Ann Molive   ICCH  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1

In [12]:
# Create a dataframe with fewer columns (to be used next)
narrower_df = pd.DataFrame({
    "ID": [6781111, 6781112],
    "Name": ["Jacky Chow", "Jet Loo"]
    })
narrower_df

        ID        Name
0  6781111  Jacky Chow
1  6781112     Jet Loo

```df1``` has columns: `ID`, `Name`, `Major`, `GPA`<br>
```narrower_df``` has columns: `ID`, `Name`<br>
Data will be concatenated nicely, and the one that doesn't have data will be ```NaN```.

In [13]:
dfx = pd.concat([df1, narrower_df])
dfx

        ID            Name  Major  GPA
0  6780001      Ann Molive   ICCH  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1
0  6781111      Jacky Chow    NaN  NaN
1  6781112         Jet Loo    NaN  NaN

The image below summarizes the operation above.<br>
<img src="https://drive.google.com/uc?export=view&id=1wILEZi4X7mwc3j0VV2dV99GQOREHU4Pl" width="50%">

#### Case II : totally different

In [14]:
# Create a dataframe with totally different columns (to be used next)
another_df = pd.DataFrame({
    "Hobby": ["Reading", "Running"],
    "Club": ["Board Game", "Debate"]
    })
another_df

     Hobby        Club
0  Reading  Board Game
1  Running      Debate

```df1``` &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; has columns: ```ID, Name Major, GPA```<br>
```another_df``` has  columns: ```..................., Hobby, Club```

There will be all columns from both dataframes. For each row, any missing values from newly added columns will be NaN (aka missing).

In [15]:
dfy = pd.concat([df1, another_df])
dfy

          ID            Name  Major  GPA    Hobby        Club
0  6780001.0      Ann Molive   ICCH  3.2      NaN         NaN
1  6780002.0      Ben Kenobi   ICJD  NaN      NaN         NaN
2  6780003.0   Peter Cruiser   ICBA  3.3      NaN         NaN
3  6780004.0      Bob Hanger   ICFS  3.5      NaN         NaN
4  6780005.0        Moe Otto   ICCS  3.1      NaN         NaN
0        NaN             NaN    NaN  NaN  Reading  Board Game
1        NaN             NaN    NaN  NaN  Running      Debate

#### Case III : some columns are the same

In [16]:
# Create a dataframe with some columns are the same (to be used next)
foo_df = pd.DataFrame({
    "ID":[6780101, 6780102],
    "Major": ["ICCH", "ICCS"],
    "Weight": [65, 59],
    "Height": [170, 180]})
foo_df

        ID Major  Weight  Height
0  6780101  ICCH      65     170
1  6780102  ICCS      59     180

```df1``` has&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;columns: ```ID, Name, Major, GPA```<br>
```foo_df``` has  columns: ```ID, ..... Major, .... Weight, Height```<br>
Notice the results, those same columns will have data from both Dataframe objects.

In [17]:
dfz = pd.concat([df1, foo_df])
dfz

        ID            Name  Major  GPA  Weight  Height
0  6780001      Ann Molive   ICCH  3.2     NaN     NaN
1  6780002      Ben Kenobi   ICJD  NaN     NaN     NaN
2  6780003   Peter Cruiser   ICBA  3.3     NaN     NaN
3  6780004      Bob Hanger   ICFS  3.5     NaN     NaN
4  6780005        Moe Otto   ICCS  3.1     NaN     NaN
0  6780101             NaN   ICCH  NaN    65.0   170.0
1  6780102             NaN   ICCS  NaN    59.0   180.0

###`inner`

What if we only care for columns that appear on both dataframes? Only columns with values appear on both dfs will be here.


```df1``` has&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;columns: ```ID, Name, Major, GPA```

```foo_df``` has  columns: ```ID, ..... Major, .... Weight, Height```


Notice only ID,Major are created.

In [18]:
dfz = pd.concat([df1, foo_df], join="inner")
dfz

        ID  Major
0  6780001   ICCH
1  6780002   ICJD
2  6780003   ICBA
3  6780004   ICFS
4  6780005   ICCS
0  6780101   ICCH
1  6780102   ICCS

- The `inner` keyword will look at the structures of both dataframes. If any columns are available on both, those columns will be in the result.
- Hence, this is **structural**.
- It doesn't look at the value inside the cells. Let's try to test it. We will set one cell as NaN (missing). We will see what happens.

In [19]:
# Let's force 6780001 (Ann Molive) to have NaN in major field
df1.loc[0, 'Major'] = np.nan
df1

        ID            Name  Major  GPA
0  6780001      Ann Molive    NaN  3.2
1  6780002      Ben Kenobi   ICJD  NaN
2  6780003   Peter Cruiser   ICBA  3.3
3  6780004      Bob Hanger   ICFS  3.5
4  6780005        Moe Otto   ICCS  3.1

In [20]:
foo_df

        ID Major  Weight  Height
0  6780101  ICCH      65     170
1  6780102  ICCS      59     180

```df1``` has&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;columns: ```ID, Name, Major, GPA```<br>
```foo_df``` has  columns: ```ID, ..... Major, .... Weight, Height```<br>


Notice that the result have NaN in the cell. ```concat``` doesn't concatenate based on value, but on structures.

In [21]:
dfz = pd.concat([df1, foo_df], join="inner")
dfz

        ID  Major
0  6780001    NaN
1  6780002   ICJD
2  6780003   ICBA
3  6780004   ICFS
4  6780005   ICCS
0  6780101   ICCH
1  6780102   ICCS

### outer
is the default value of the ```concat``` function.

So, we don't need to specify it. Leaving it blank is the same as setting join="outer"

```df1``` has&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;columns: ```ID, Name, Major, GPA```<br>
```foo_df``` has  columns: ```ID, ..... Major, .... Weight, Height```

In [22]:
dfz = pd.concat([df1, foo_df], join="outer")
dfz

        ID            Name  Major  GPA  Weight  Height
0  6780001      Ann Molive    NaN  3.2     NaN     NaN
1  6780002      Ben Kenobi   ICJD  NaN     NaN     NaN
2  6780003   Peter Cruiser   ICBA  3.3     NaN     NaN
3  6780004      Bob Hanger   ICFS  3.5     NaN     NaN
4  6780005        Moe Otto   ICCS  3.1     NaN     NaN
0  6780101             NaN   ICCH  NaN    65.0   170.0
1  6780102             NaN   ICCS  NaN    59.0   180.0

### Adding Columns

The following code is for **Google Colab** only.

In [23]:
CSV_URL = 'https://drive.google.com/uc?export=download&id='
# Load concat_1.csv
df1 = pd.read_csv(CSV_URL + '1V6MG7Wecmvh-tgwojTqwu0HUVYhihHQ9')
# Load concat_2.csv
df2 = pd.read_csv(CSV_URL + '12ZEScK0XGAVR0TXwsKLVoI3HsAL1c9ko')
# Load concat_3.csv
df3 = pd.read_csv(CSV_URL + '1bJV3IleIN-GC-k-I07eKfIAa_dmanKCD')

In [24]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [25]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [26]:
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

Calling concat will just append rows below as we have seen earlier.

In [27]:
row_concat = pd.concat([df1, df2, df3])
row_concat

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

### What if we want to add along the direction of column?
#### Adding all columns by concat with axis = 0
axis 0 is "row".
data with the same row labels will be in the same row

In [28]:
col_concat = pd.concat([df1, df2, df3], axis=1)
col_concat

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [29]:
col_concat['A']

    A   A    A
0  A0  A4   A8
1  A1  A5   A9
2  A2  A6  A10
3  A3  A7  A11

#### Adding columns with different indexes

First, let's rename the column names

In [30]:
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

In [31]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [32]:
df2

    D   E   F   G
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [33]:
df3

     A    D    G    H
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [34]:
# df1 has columns: A,B,C,D
# df2 has columns:       D,E,F,G
# df3 has columns: A,    D,    G,H
# notice when columns appear on multiple dataframes
row_concat = pd.concat([df1, df2, df3])
row_concat

     A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN   A4   B4   C4   D4  NaN
1  NaN  NaN  NaN   A5   B5   C5   D5  NaN
2  NaN  NaN  NaN   A6   B6   C6   D6  NaN
3  NaN  NaN  NaN   A7   B7   C7   D7  NaN
0   A8  NaN  NaN   B8  NaN  NaN   C8   D8
1   A9  NaN  NaN   B9  NaN  NaN   C9   D9
2  A10  NaN  NaN  B10  NaN  NaN  C10  D10
3  A11  NaN  NaN  B11  NaN  NaN  C11  D11

In [35]:
# df1 has columns: A,B,C,D
# df2 has columns:       D,E,F,G
# df3 has columns: A,    D,    G,H
# Notice that all dataframes have column D
row_concat = pd.concat([df1, df2, df3], join='inner')
row_concat

     D
0   D0
1   D1
2   D2
3   D3
0   A4
1   A5
2   A6
3   A7
0   B8
1   B9
2  B10
3  B11

#### In what situation we can use this method?
Sometimes, we have dataframs that carry differnt number of columns. If both of them carry the same important columns, we may want to do the "inner" join so eliminate extra columns from each dataframe.

In [36]:
# Create a dataframe to be used next
addr1_df = pd.DataFrame({
    "Number":["114", "153/1", "102", "945"],
    "Building":["A", "Beach Front", "Main bldg", "C"],
    "Street":["Sai 4", "Rama IX", "Sai 3", "Baromratchonnee"],
    "City":["Salaya", "Payathai", "Salaya", "Aroonamarin"],
    "District":["Taweewattana", "Ratchtevee", "Taweewattana", "Bangkok Noi"],
    "Province":["Bangkok", "Bangkok", "Bangkok", "Bangkok"],
    "ZIP":[73710, 10400, 73710, 10700]})

addr1_df

,Number,Building,Street,City,District,Province,ZIP
0,114,A,Sai 4,Salaya,Taweewattana,Bangkok,73710
1,153/1,Beach Front,Rama IX,Payathai,Ratchtevee,Bangkok,10400
2,102,Main bldg,Sai 3,Salaya,Taweewattana,Bangkok,73710
3,945,C,Baromratchonnee,Aroonamarin,Bangkok Noi,Bangkok,10700

In [37]:
# Create a dataframe to be used next
addr2_df = pd.DataFrame({
    "Number":["208", "2491", "327", "123"],
    "Street":["Rama VI", "Rama I", "Sukhumvit", "Charansanitwong"],
    "City":["SamSen Nai", "Bangrug", "Prakanong", "Bangplud"],
    "District":["Phayathai", "Ratchtevee", "Taweewattana", "Bangkok Noi"],
    "Province":["Bangkok", "Bangkok", "Bangkok", "Bangkok"],
    "Country":["Thailand", "Thailand", "Thailand", "Thailand"],
    "ZIP":[10100, 10400, 10600, 10200]
})
addr2_df

  Number           Street        City      District Province   Country    ZIP
0    208          Rama VI  SamSen Nai     Phayathai  Bangkok  Thailand  10100
1   2491           Rama I     Bangrug    Ratchtevee  Bangkok  Thailand  10400
2    327        Sukhumvit   Prakanong  Taweewattana  Bangkok  Thailand  10600
3    123  Charansanitwong    Bangplud   Bangkok Noi  Bangkok  Thailand  10200

In [38]:
# If we concat with default join ("outer"), we will get many fields with NaN
addr_df = pd.concat([addr1_df, addr2_df])
addr_df

,Number,Building,Street,City,District,Province,ZIP,Country
0,114,A,Sai 4,Salaya,Taweewattana,Bangkok,73710,NaN
1,153/1,Beach Front,Rama IX,Payathai,Ratchtevee,Bangkok,10400,NaN
2,102,Main bldg,Sai 3,Salaya,Taweewattana,Bangkok,73710,NaN
3,945,C,Baromratchonnee,Aroonamarin,Bangkok Noi,Bangkok,10700,NaN
0,208,NaN,Rama VI,SamSen Nai,Phayathai,Bangkok,10100,Thailand
1,2491,NaN,Rama I,Bangrug,Ratchtevee,Bangkok,10400,Thailand
2,327,NaN,Sukhumvit,Prakanong,Taweewattana,Bangkok,10600,Thailand
3,123,NaN,Charansanitwong,Bangplud,Bangkok Noi,Bangkok,10200,Thailand

In [39]:
# This is more concise
addr_df = pd.concat([addr1_df, addr2_df], join="inner")
addr_df

  Number           Street         City      District Province    ZIP
0    114            Sai 4       Salaya  Taweewattana  Bangkok  73710
1  153/1          Rama IX     Payathai    Ratchtevee  Bangkok  10400
2    102            Sai 3       Salaya  Taweewattana  Bangkok  73710
3    945  Baromratchonnee  Aroonamarin   Bangkok Noi  Bangkok  10700
0    208          Rama VI   SamSen Nai     Phayathai  Bangkok  10100
1   2491           Rama I      Bangrug    Ratchtevee  Bangkok  10400
2    327        Sukhumvit    Prakanong  Taweewattana  Bangkok  10600
3    123  Charansanitwong     Bangplud   Bangkok Noi  Bangkok  10200

#### Concatenate Columns With Different Rows

In [40]:
# Change the row labels.
df1.index = [0, 1, 2, 3]
df2.index = [2, 3, 4, 5]
df3.index = [2, 3, 6, 7]

In [41]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [42]:
df2

    D   E   F   G
2  A4  B4  C4  D4
3  A5  B5  C5  D5
4  A6  B6  C6  D6
5  A7  B7  C7  D7

In [43]:
df3

     A    D    G    H
2   A8   B8   C8   D8
3   A9   B9   C9   D9
6  A10  B10  C10  D10
7  A11  B11  C11  D11

In [44]:
# df1 has rows: 0,1,2,3
# df2 has rows:     2,3,4,5
# df3 has rows:     2,3,   6,7
col_concat = pd.concat([df1, df2, df3], axis=1)
col_concat

     A    B    C    D    D    E    F    G    A    D    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A4   B4   C4   D4   A8   B8   C8   D8
3   A3   B3   C3   D3   A5   B5   C5   D5   A9   B9   C9   D9
4  NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

Notice that the row labels indicate what data will be in that row. At the end, we have row 0, 1, 2, 3, 4, 5, 6, and 7.

Also, notice the column labels, many of them have the same name !!!

In [45]:
# select columns with label "A" out
col_concat["A"]

     A    A
0   A0  NaN
1   A1  NaN
2   A2   A8
3   A3   A9
4  NaN  NaN
5  NaN  NaN
6  NaN  A10
7  NaN  A11

In [46]:
# set join = "inner"
# if we want only rows that appear in all dataframes
col_concat = pd.concat([df1, df2, df3], axis=1, join="inner")
col_concat

    A   B   C   D   D   E   F   G   A   D   G   H
2  A2  B2  C2  D2  A4  B4  C4  D4  A8  B8  C8  D8
3  A3  B3  C3  D3  A5  B5  C5  D5  A9  B9  C9  D9

In [47]:
pd.concat([df2, df1, df3], axis=1)

     D    E    F    G    A    B    C    D    A    D    G    H
2   A4   B4   C4   D4   A2   B2   C2   D2   A8   B8   C8   D8
3   A5   B5   C5   D5   A3   B3   C3   D3   A9   B9   C9   D9
4   A6   B6   C6   D6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5   A7   B7   C7   D7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN   A1   B1   C1   D1  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [48]:
pd.concat([df1, df2, df3], axis=0)

     A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN   A4   B4   C4   D4  NaN
3  NaN  NaN  NaN   A5   B5   C5   D5  NaN
4  NaN  NaN  NaN   A6   B6   C6   D6  NaN
5  NaN  NaN  NaN   A7   B7   C7   D7  NaN
2   A8  NaN  NaN   B8  NaN  NaN   C8   D8
3   A9  NaN  NaN   B9  NaN  NaN   C9   D9
6  A10  NaN  NaN  B10  NaN  NaN  C10  D10
7  A11  NaN  NaN  B11  NaN  NaN  C11  D11

### Recap on `concat`

- Concatenate `DataDrame` objects
- Three commonly-used paprameters:
    - **`axis`**
        - 0 by default, row-wise cacatneation
        - 1 = column-wise cacatneation
    - **`ignore_index`**
        - If`True`, source objects' indices are ignore, and 0, 1, 2, ... will be used instead.
    - **`join`**
        - **`outer`**: the default axis
        - **`inner`**: keeps only rows and/or columns with shared labels/indices

## Merging - Combining dataframes based on values
There will be cases that we need to merge data in a more specific way. Pandas provide many functions to do this.

We will use data from the reference textbook of this course, "Pandas for Everyone".<br>
Alternative resource: [Combining Datasets: Merge and Join](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html)

The following code is for Google Colab only. If you use a desktop IDE,
1. Download the data files from https://drive.google.com/drive/folders/1all1VgS-0bFr9uB27NWG8UXzrIBTh2Xl?usp=sharing
2. Replace both lines below with your local file paths, such as
```python
person = pd.read_csv("./datasets/survey_person.csv")
site = pd.read_csv("./datasets/survey_site.csv")
survey = pd.read_csv("./datasets/survey_survey.csv")
visited = pd.read_csv("./datasets/survey_visited.csv")
```

In [49]:
# Load the file survey_person.csv
person = pd.read_csv(CSV_URL + '1OMsps89VPOY_egCvhI9gLLULngGqDdBH')
# Load the file survey_site.csv
site = pd.read_csv(CSV_URL + '1isk_-IhK0BWkr2pTpNSQkID6JoiZmrDO')
# Load the file survey_survey.csv
survey = pd.read_csv(CSV_URL + '1gHjkhtDOzdd-D_IK-W12L3pQOH_nwqcn')
# Load the file survey_visited.csv
visited = pd.read_csv(CSV_URL + '1XX_FdD36zk7IgFeeOBEY5wfsAn4TCtwd')

In [50]:
person

      ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth

In [51]:
site

    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [52]:
survey

    taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [53]:
visited

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

### One-to-One Merge
The column we wants to join has no duplicated value.
Each value in the join-column of the left dataframe occurs once.
Each value in the join-column of the right dataframe occurs once.

Notice each value of the **name** column of the **site** dataframe occurs only once.

Notice each value of the **site** column of the **visited_subset** dataframe occurs only once.

In [54]:
# Let's select only some rows, so it is easier to observe changes
visited_subset = visited.loc[[0, 2, 6], ]
visited_subset

   ident   site       dated
0    619   DR-1  1927-02-08
2    734   DR-3  1939-01-07
6    837  MSK-4  1932-01-14

In [55]:
# Notice the site column here
site

    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [56]:
# LEFT  dataframe: site           : has columns:       name,lat,long
# RIGHT dataframe: visited_subset : has columns: ident,site,         dated
#
# noted: both dataframes have different names to store the site name.
# In terms of value: LEFT->name is the same as RIGHT->site
one2one_merge = site.merge(visited_subset, left_on="name", right_on="site")
one2one_merge

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
2  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

> Find rows where the left table's  name  equals the right table's  site , then
> combine their information.

In [57]:
one2one_join = site.join(visited_subset)
one2one_join

    name    lat    long  ident  site       dated
0   DR-1 -49.85 -128.57  619.0  DR-1  1927-02-08
1   DR-3 -47.15 -126.72    NaN   NaN         NaN
2  MSK-4 -48.87 -123.40  734.0  DR-3  1939-01-07

> Match rows using their **index** labels, and add the right table's columns.

### Many-to-One Merge
One of the dataframes has repeat values.

Notice (in the cell below) some values of the **site** column of the **visited** dataframe occurs more than once (such as DR-3).

Notice each value of the **name** column of the **site** dataframe occurs only once (such as DR-3 here appears only once).

In [58]:
# Let's modify visited a bit, we will see the effect that next
visited.loc[2, 'site'] = np.nan
visited

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734    NaN  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

*References*
- [Merge Two pandas DataFrames in Python (6 Examples)(https://statisticsglobe.com/merge-two-pandas-dataframes-python)
- https://deepage.net/features/pandas-merge.html

| Join | Description |
|---|---|
| `Left` | _Keep all the keys from the left_ |
| `Right` | _Keep all the keys from the right_ |
| `outer` | _Keep all the keys from both left and right_ |
| `inner` | _Keep only keys that exist in both left and right_ |

In [59]:
site

    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40

In [60]:
# LEFT: visited has columns: ident,site,dated
# RIGHT: site has   columns:                  name,lat, long
Many2One_merge = visited.merge(site, left_on="site", right_on='name')
Many2One_merge

   ident   site       dated   name    lat    long
0    619   DR-1  1927-02-08   DR-1 -49.85 -128.57
1    622   DR-1  1927-02-10   DR-1 -49.85 -128.57
2    735   DR-3  1930-01-12   DR-3 -47.15 -126.72
3    751   DR-3  1930-02-26   DR-3 -47.15 -126.72
4    752   DR-3         NaN   DR-3 -47.15 -126.72
5    837  MSK-4  1932-01-14  MSK-4 -48.87 -123.40
6    844   DR-1  1932-03-22   DR-1 -49.85 -128.57

Notice the result will have columns: ident,site,dated,name,lat,long
For each row in LEFT, it'll look at the value in column "site" of that row.
With this value, it will look in to the table from the RIGHT.
If there is a match, the row from the right will be added (=more columns)
If there is no match, it won't show up here.

### One-to-Many Merge
The concept is the same, we just swap the order

In [61]:
# LEFT: site has columns: name,lat, long
# RIGHT: visited has columns: ident,site,dated
One2Many_merge = site.merge(visited, left_on="name", right_on='site')
One2Many_merge

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
4   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
5   DR-3 -47.15 -126.72    752   DR-3         NaN
6  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

For each row in LEFT, it'll look at the value in column "name" of that row.
With this value, it will look in to the table from the RIGHT.
- If there is a match, the row from the right will be added (= more columns)
- If there is no match, it won't show up here.
- Where there are multiple matches, the right appear in more than one row.
- For each successful match, it will become one row.

### Many-to-Many Merge
The data on both sides contain duplicated values.

Let's start with a Many-to-One

In [62]:
# Create a dataframe to be used next
# Notice that the many students take the same course

enrollment_df = pd.DataFrame({
    "ID": [1001,1002],
    "Course": ["ICCS161", "ICCS161"]
})
enrollment_df

     ID   Course
0  1001  ICCS161
1  1002  ICCS161

In [63]:
# Create another dataframe to be used next
# Notice that one course has many exams

exam_df = pd.DataFrame({
    "Course": ["ICCS161", "ICCS161"],
    "Exam": ["Midterm", "Final"]
})
exam_df

    Course     Exam
0  ICCS161  Midterm
1  ICCS161    Final

In [64]:
# MANY-TO-MANY
# LEFT: enrollment_df
# RIGHT: exam_df
Many2Many_merge = enrollment_df.merge(exam_df, left_on="Course",right_on="Course")
Many2Many_merge

     ID   Course     Exam
0  1001  ICCS161  Midterm
1  1001  ICCS161    Final
2  1002  ICCS161  Midterm
3  1002  ICCS161    Final

For each row in LEFT, it'll look at the value in column "Course" of that row.
With this value, it will look in to the table from the RIGHT.
- If there is a match, the row from the right will be added (=more columns)
- If there is no match, it won't show up here.
- Where, there are multiple matches. Since the right appear in more than one row.
- For each successful match, it will become one row.

This is called Many-to-Many because MANY students enroll the same course.
One Course has many exams (midterm & final). Therefore, when we think about  STUDETS---EXAM. That's many to many.

Let's consider another example.

In [65]:
enrollment_df_2 = pd.DataFrame({
    "ID": [1001, 1002, 1003],
    "Course": ["ICCS161", "ICCS161", "ICCS331"]
})
enrollment_df_2

     ID   Course
0  1001  ICCS161
1  1002  ICCS161
2  1003  ICCS331

In [66]:
Many2Many_merge_2 = enrollment_df_2.merge(exam_df, left_on="Course", right_on="Course")
Many2Many_merge_2

     ID   Course     Exam
0  1001  ICCS161  Midterm
1  1001  ICCS161    Final
2  1002  ICCS161  Midterm
3  1002  ICCS161    Final

### `merge`'s Parameters

![`inner` vs `outer`](https://i.sstatic.net/1rb1R.jpg)<br>Ref: [pandas Merging 101](https://stackoverflow.com/questions/53645882/pandas-merging-101)

###`join`

So far we have worked with dataframes with no row labels. Let's add them and see the effect of the index label. Now we can perform <code>join()</code> that combines columns of two dataframes with different indices.

<table>
    <tr>
        <td><img src="https://i.sstatic.net/3qpXx.gif"></td>
        <td><img src="https://i.sstatic.net/dG8mw.gif"></td>
    </tr>
    <tr>
        <td><img src="https://i.sstatic.net/JpPRH.gif"></td>
        <td><img src="https://i.sstatic.net/s5hgJ.gif"></td>
    </tr>
</table>

Ref: [pandas Merging 101](https://stackoverflow.com/questions/53645882/pandas-merging-101)

In [67]:
enrollment_df_2.set_index('Course', inplace=True)
enrollment_df_2

           ID
Course
ICCS161  1001
ICCS161  1002
ICCS331  1003

In [68]:
exam_df.set_index('Course', inplace=True)
exam_df

            Exam
Course
ICCS161  Midterm
ICCS161    Final

In [69]:
Many2Many_merge_3 = enrollment_df_2.join(exam_df, how="outer")
Many2Many_merge_3

           ID     Exam
Course
ICCS161  1001  Midterm
ICCS161  1001    Final
ICCS161  1002  Midterm
ICCS161  1002    Final
ICCS331  1003      NaN

In [70]:
Many2Many_merge_3 = enrollment_df_2.join(exam_df, how="inner")
Many2Many_merge_3

           ID     Exam
Course
ICCS161  1001  Midterm
ICCS161  1001    Final
ICCS161  1002  Midterm
ICCS161  1002    Final

### Conclusions

#### Similarities and Differences of `concat`, `merge`, `join`

Find the operation equivalent to the LHS.

In [71]:
import pandas as pd

CSV_URL = 'https://drive.google.com/uc?export=download&id='
# Load concat_1.csv
df1 = pd.read_csv(CSV_URL + '1V6MG7Wecmvh-tgwojTqwu0HUVYhihHQ9')
# Load concat_2.csv
df2 = pd.read_csv(CSV_URL + '12ZEScK0XGAVR0TXwsKLVoI3HsAL1c9ko')

In [72]:
df3 = df2.copy()

df3.iloc[2] = df1.iloc[1]
df3.iloc[3] = df1.iloc[2]

df2.columns = ['D', 'E', 'F', 'G']
df3.columns = ['A', 'D', 'G', 'H']

df2.index=[0, 2, 3, 5]
df3.index=[2, 3, 6, 7]

In [73]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [74]:
df2

    D   E   F   G
0  A4  B4  C4  D4
2  A5  B5  C5  D5
3  A6  B6  C6  D6
5  A7  B7  C7  D7

In [75]:
df3

    A   D   G   H
2  A4  B4  C4  D4
3  A5  B5  C5  D5
6  A1  B1  C1  D1
7  A2  B2  C2  D2

In [76]:
pd.concat([df1, df2])

     A    B    C   D    E    F    G
0   A0   B0   C0  D0  NaN  NaN  NaN
1   A1   B1   C1  D1  NaN  NaN  NaN
2   A2   B2   C2  D2  NaN  NaN  NaN
3   A3   B3   C3  D3  NaN  NaN  NaN
0  NaN  NaN  NaN  A4   B4   C4   D4
2  NaN  NaN  NaN  A5   B5   C5   D5
3  NaN  NaN  NaN  A6   B6   C6   D6
5  NaN  NaN  NaN  A7   B7   C7   D7

In [77]:
pd.concat([df1, df2], axis=1)

     A    B    C    D    D    E    F    G
0   A0   B0   C0   D0   A4   B4   C4   D4
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A5   B5   C5   D5
3   A3   B3   C3   D3   A6   B6   C6   D6
5  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [78]:
pd.concat([df1, df2], join='inner')

    D
0  D0
1  D1
2  D2
3  D3
0  A4
2  A5
3  A6
5  A7

In [79]:
pd.concat([df1, df2], axis=1, join='inner')

    A   B   C   D   D   E   F   G
0  A0  B0  C0  D0  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5
3  A3  B3  C3  D3  A6  B6  C6  D6

In [80]:
df1.join(df2, lsuffix="_left", rsuffix="_right", how='outer')

     A    B    C D_left D_right    E    F    G
0   A0   B0   C0     D0      A4   B4   C4   D4
1   A1   B1   C1     D1     NaN  NaN  NaN  NaN
2   A2   B2   C2     D2      A5   B5   C5   D5
3   A3   B3   C3     D3      A6   B6   C6   D6
5  NaN  NaN  NaN    NaN      A7   B7   C7   D7

In [81]:
pd.merge(df1, df2, left_index=True, right_index=True)

    A   B   C D_x D_y   E   F   G
0  A0  B0  C0  D0  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5
3  A3  B3  C3  D3  A6  B6  C6  D6

In [82]:
df1.join(df2, lsuffix="_left", rsuffix="_right", how='left')

    A   B   C D_left D_right    E    F    G
0  A0  B0  C0     D0      A4   B4   C4   D4
1  A1  B1  C1     D1     NaN  NaN  NaN  NaN
2  A2  B2  C2     D2      A5   B5   C5   D5
3  A3  B3  C3     D3      A6   B6   C6   D6

In [83]:
pd.merge(df1, df2, left_index=True, right_index=True, how='left')

    A   B   C D_x  D_y    E    F    G
0  A0  B0  C0  D0   A4   B4   C4   D4
1  A1  B1  C1  D1  NaN  NaN  NaN  NaN
2  A2  B2  C2  D2   A5   B5   C5   D5
3  A3  B3  C3  D3   A6   B6   C6   D6