<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/Copy_of_pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas - DataFrame
*B. Mathayomchan and K. Bunchongchit*<br>
Last edited on January 8, 2026

## Topics:
What is a DataFrame?

1. CREATE
2. READ
3. UPDATE
4. DELETE

In [ ]:
import pandas as pd
import numpy as np

## What is a DataFrame?
DataFrame is a Data in a table form (like a spreadsheet) where all data points in the same column have the same type.

<img src="https://pynative.com/wp-content/uploads/2021/02/dataframe.png" width=50% />

In [ ]:
df = pd.DataFrame({
    'Gold': [15, 12, 10],
    'Silver': [11, 9, 5] ,
    'Bronze': [6, 8, 12],
    'Continent': ['Europe', 'Asia', 'Asia']
    },
    ['France','China','Thailand'])
df

          Gold  Silver  Bronze Continent
France      15      11       6    Europe
China       12       9       8      Asia
Thailand    10       5      12      Asia

## 1. CREATE
The simple way to create a dataframe from scratch is by using a dictionary. A dictionary holds key:value where **key** is column name. The **value** is a **list** of data points.

<img src="https://av-eks-blogoptimized.s3.amazonaws.com/17699Append-a-Dictionary-to-a-list-in-Python-5-i2tutorials.png" />

In [ ]:
my_dt = {
    'Gold': [15, 12, 10],
    'Silver': [11, 9, 5] ,
    'Bronze': [6, 8, 12],
    'Continent': ['Europe', 'Asia', 'Asia']
}
df1 = pd.DataFrame(my_dt)
df1

   Gold  Silver  Bronze Continent
0    15      11       6    Europe
1    12       9       8      Asia
2    10       5      12      Asia

Notice that the index of the row is a number. This is called **the label index**. As the word **label** may hint us already, we can set **the label index** to string as well.

In [ ]:
my_list = ['France', 'China', 'Thailand']
df2 = pd.DataFrame(my_dt, my_list)
df2

          Gold  Silver  Bronze Continent
France      15      11       6    Europe
China       12       9       8      Asia
Thailand    10       5      12      Asia

Create a dataframe by manually setting each column with a series.

In [ ]:
df3 = pd.DataFrame()              # Start with empty dataframe
ser1 = pd.Series([15, 11, 6])     # Create a series from a list
ser2 = pd.Series([11, 9, 5])      # Create a series from a list
ser3 = pd.Series([10, 5, 2])      # Create a series from a list
ser4 = pd.Series(["Europe", "Asia", "Asia"])  # Create a series from a list

df3["Gold"] = ser1
df3["Silver"] = ser2
df3["Bronze"] = ser3
df3["Continent"] = ser4

df3

   Gold  Silver  Bronze Continent
0    15      11      10    Europe
1    11       9       5      Asia
2     6       5       2      Asia

In [ ]:
my_index = pd.Series(["France", "China", "Thailand"])  # Create a series from a list
# inplace indicates Python to save the result into the caller variable
df33 = df3.set_index(my_index)
df33

          Gold  Silver  Bronze Continent
France      15      11      10    Europe
China       11       9       5      Asia
Thailand     6       5       2      Asia

In [ ]:
df3

   Gold  Silver  Bronze Continent
0    15      11      10    Europe
1    11       9       5      Asia
2     6       5       2      Asia

In [ ]:
# Create a series from a list
my_index = pd.Series(["France", "China", "Thailand"])
# inplace indicates Python to save the result into the caller variable
# df3 = df3.set_index(my_index)
df3.set_index(my_index, inplace=True)
df3

          Gold  Silver  Bronze Continent
France      15      11      10    Europe
China       11       9       5      Asia
Thailand     6       5       2      Asia

## 2 READ
    2.1 Subsetting columns
        - Subsetting one column
        - Subsetting multiple columns
    2.2 Subsetting rows
        - Subsetting rows when numbers are used as the label index
        - Subsetting rows when labels are used as the label index
    2.3 Subsetting both rows and columns
    2.4 Accessing any particular element

### 2.1 Subsetting columns
**Subsetting one column**: We can subset a column out by column name.
```
df['column_name']
```

In [ ]:
df3

          Gold  Silver  Bronze Continent
France      15      11      10    Europe
China       11       9       5      Asia
Thailand     6       5       2      Asia

In [ ]:
df3['Continent']

France      Europe
China         Asia
Thailand      Asia
Name: Continent, dtype: object

In [ ]:
df3['Continent'].shape

(3,)

In [ ]:
df3[['Continent']]

         Continent
France      Europe
China         Asia
Thailand      Asia

In [ ]:
print(type(df3['Continent']), type(df3[['Continent']]))

<class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'>

**Prompt**: What is the difference between ```df3['Continent']``` and ```df3[['Continent']]```?

In [ ]:
print(df3)

          Gold  Silver  Bronze Continent
France      15      11      10    Europe
China       11       9       5      Asia
Thailand     6       5       2      Asia

**Prompt**: Which printing is the result of __str__ and which one __repr__?


1.   ```df3```
2.   ```print(df3)```

**Subsetting multiple columns :** We can subset multiple columns by a list of column names.
```
df[['col_name1', 'col_name2',..., 'col_namen']]
```

In [ ]:
df1[['Gold', 'Continent']]

   Gold Continent
0    15    Europe
1    12      Asia
2    10      Asia

In [ ]:
df1['Gold', 'Continent']

KeyError: ('Gold', 'Continent')

### 2.2 Subsetting rows
**Subsetting rows when numbers are used as the label index**

We can use  **```loc['index_label']```** to subset the row.

The **index labels** of df1 are numbers. We can subset the row by the numbers.

In [ ]:
df1

   Gold  Silver  Bronze Continent
0    15      11       6    Europe
1    12       9       8      Asia
2    10       5      12      Asia

In [ ]:
df1.loc[0]

Gold             15
Silver           11
Bronze            6
Continent    Europe
Name: 0, dtype: object

In [ ]:
df1[0]

KeyError: 0

In [ ]:
type(df1.loc[0])

pandas.core.series.Series

In [ ]:
df1.loc[1]  # returns a series

Gold           12
Silver          9
Bronze          8
Continent    Asia
Name: 1, dtype: object

In [ ]:
df1.loc[[1]]  # returns a dataframe

   Gold  Silver  Bronze Continent
1    12       9       8      Asia

In [ ]:
df1.loc[1:3]  # We can slice them too

   Gold  Silver  Bronze Continent
1    12       9       8      Asia
2    10       5      12      Asia

**Subsetting rows when labels are used as the label index**

We can use  **```loc['label_based_index']```** to subset the row.

If there are multiple rows, we can use a set of label.

_Note: df2 has strings as the index labels._

In [ ]:
df2

          Gold  Silver  Bronze Continent
France      15      11       6    Europe
China       12       9       8      Asia
Thailand    10       5      12      Asia

In [ ]:
df2.loc['China']

Gold           12
Silver          9
Bronze          8
Continent    Asia
Name: China, dtype: object

In [ ]:
df2.loc[['China', 'France']]

        Gold  Silver  Bronze Continent
China     12       9       8      Asia
France    15      11       6    Europe


**What if the dataframe uses string as the label index, but we need to subset many rows out?**

- Do we need to make a list of the countries we want?
- There are 193 countries in the world, I want the top 50.
- Typing a list of 50 country names is tedious.
- We can still subset it by the number using **```iloc[ ]```**.

In [ ]:
df2.loc[1:3]  # ERROR. Label is not number

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [ ]:
df2.iloc[1:3]  # iloc saves the day

          Gold  Silver  Bronze Continent
China       12       9       8      Asia
Thailand    10       5      12      Asia

### 2.3 Both rows and columns
As we just learn that we can use ```iloc[ ]``` to subset data.

We can apply the same method to subset both rows and columns.

Normally, we use indexes to do slicing.

**```df.iloc[row_slicing, column_slicing]```**

In [ ]:
df2.iloc[:, 0:1]  # all rows, first column

          Gold
France      15
China       12
Thailand    10

In [ ]:
df2.iloc[:, 0]

France      15
China       12
Thailand    10
Name: Gold, dtype: int64

**Prompt**: What is the difference between ```df2.iloc[:, 0:1]``` and ```df2.iloc[:, 0]```?

In [ ]:
print(type(df2.iloc[:, 0:1]), type(df2.iloc[:, 0]))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>

In [ ]:
df2.iloc[:, 1:]  # all rows, second column to the end

          Silver  Bronze Continent
France        11       6    Europe
China          9       8      Asia
Thailand       5      12      Asia

In [ ]:
df2.iloc[:, 1:-1]  # all rows, second column to the penultimate column

          Silver  Bronze
France        11       6
China          9       8
Thailand       5      12

In [ ]:
df2.iloc[:2, :]  # first two rows, all columns

        Gold  Silver  Bronze Continent
France    15      11       6    Europe
China     12       9       8      Asia

In [ ]:
df2.iloc[:2, [0, 3]]  # first two rows, only the Gold and Continent

        Gold Continent
France    15    Europe
China     12      Asia

### 2.4 Accessing any particular element
After we subset a row out, that row is actually a series. Therefore, we can access the element easily by using index.

In [ ]:
x = df2.iloc[2]
x

Gold           10
Silver          5
Bronze         12
Continent    Asia
Name: Thailand, dtype: object

In [ ]:
type(x)

pandas.core.series.Series

In [ ]:
x.iloc[2]  # Let's access the number of Bronze (index )

np.int64(12)

In [ ]:
df2.iloc[2, 2]

np.int64(12)

In [ ]:
df2

          Gold  Silver  Bronze Continent
France      15      11       6    Europe
China       12       9       8      Asia
Thailand    10       5      12      Asia

Extract 5 from df2.

In [ ]:
df2.iloc[2, 1]

np.int64(5)

## In-class activity

Complete the activity on Canvas with your group as instructed.

## 3 UPDATE
* 3.1 Change existing value
* 3.2 Append another dataframe
* 3.3 Add another column

### 3.1 Change existing value
We can update existing value by assigning a new value to it.

In [ ]:
df2

Updating via position indices

In [ ]:
df2.iloc[1, 2] = 999
df2

Updating via labels

In [ ]:
df2.loc['Thailand', 'Silver'] = 8
df2

### 3.2 Append another dataframe
We can use <code>append( )</code> function.

In [ ]:
df2  # For an easy comparison, let's list df2 out again.

In [ ]:
dfplus = pd.DataFrame(
    {
        'Gold': [3],
        'Silver': [2] ,
        'Bronze': [0],
        'Continent': ['Europe']
    },
    ['England'])
dfplus

In [ ]:
df3 = pd.concat([df2, dfplus])
df3

In [ ]:
df2  # df2 should stay the same.

### 3.3 Add another column
Adding another series is easy. We can assign a new series to a new column label.

In [ ]:
df3["Abbreviation"] = pd.Series(['FR', 'CN', 'TH', 'UK'], index=df3.index)
df3

## 4 DELETE
* 4.1 Delete rows
* 4.2 Delete columns

In [ ]:
df2

### 4.1 Delete rows
We can use drop( label ) to delete the row.
Note: drop will return a new dataframe.

In [ ]:
df3 = df2.drop("China")
df3

In [ ]:
df2

If we want drop to happen to that dataframe, we can set inplace to True.

In [ ]:
df4 = df2.copy()  # Let's preserve df2 because we are going to delete right into the dataframe.
df4

In [ ]:
df4.drop("China", inplace=True)  # Which axis?
df4

In [ ]:
df4_2 = df2.copy()  # Let's preserve df2 because we are going to delete right into the dataframe.
df4_2 = df4_2.drop("China")
df4_2

In [ ]:
df5 = df2.drop("Thailand", axis=0)  # row or column?
df5

In [ ]:
df2  # should remain the same

### 4.2 Delete columns
We can use the same <code>drop( )</code>. This time, we just have to set axis to 1.

(the default is <code>axis=0</code> which means row)

In [ ]:
df6 = df2.copy()
df6

In [ ]:
df6.drop("Gold", axis=1, inplace=True)
df6

Can we skip the axis argument here?

In [ ]:
df7 = df2.copy()
df7.drop("France", inplace=True)