<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/missing_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Handling Missing Data in the Titanic Dataset

In this group exercise, you will practice how to deal with missing data using Seaborn's Titanic dataset.

## Process Overview
1. Understand the Titanic event.
2. Generate descriptive statistics. *(already provided)*
3. Determine the type of missing data in each column.
4. Determine the amount of missing data.
5. Decide how to deal with missing data in each column and as a whole.
   - If you need additional information, explore the internet or ask AI.
   - Record all your search queries or prompts with notes on how well they worked.
6. Perform the methods you decided in Step 5.
7. Run descriptive statistics again.
8. Compare the original descriptive stats with the cleaned dataset.
9. Conclude if your methods were suitable.
10. Ask **another Generative AI** for suggestions about your method. Record queries and notes.

## 1. Understand the Titanic event.

A. Summarize the Titanic event.
> The RMS Titanic was a British passenger ship that sank on April 15, 1912, during its maiden voyage from Southampton to New York. After striking an iceberg in the North Atlantic on April 14, the ship flooded and sank in less than three hours. Over 1,500 people died due to insufficient lifeboats and freezing water. The disaster led to major improvements in international maritime safety regulations.
>
<br>B. List your references.
> [wikipedia](https://en.wikipedia.org/wiki/Titanic)
>

*Write your answer here.*

## Step 2: Descriptive Statistics (Already Provided)
Below are the descriptive statistics of the Titanic dataset before handling missing data.

In [1]:
import seaborn as sns
import pandas as pd

# Load Titanic dataset
titanic = sns.load_dataset('titanic')

# Preview the dataset
display(titanic)
display(titanic.sample(10))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
616,0,3,male,34.0,1,1,14.4000,S,Third,man,True,NaN,Southampton,no,False
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
150,0,2,male,51.0,0,0,12.5250,S,Second,man,True,NaN,Southampton,no,True
659,0,1,male,58.0,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
73,0,3,male,26.0,1,0,14.4542,C,Third,man,True,NaN,Cherbourg,no,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
453,1,1,male,49.0,1,0,89.1042,C,First,man,True,C,Cherbourg,yes,False
848,0,2,male,28.0,0,1,33.0000,S,Second,man,True,NaN,Southampton,no,False
102,0,1,male,21.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False

In [2]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [3]:
# Descriptive statistics of numerical columns
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [4]:
# Descriptive statistics of object columns
titanic.select_dtypes(include=['object', 'category', 'bool']).describe()

/var/folders/x1/q5ftwsxd63l56l4dr27_lk2r0000gn/T/ipykernel_30090/2612592725.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  titanic.select_dtypes(include=['object', 'category', 'bool']).describe()

         sex embarked  class  who adult_male deck  embark_town alive alone
count    891      889    891  891        891  203          889   891   891
unique     2        3      3    3          2    7            3     2     2
top     male        S  Third  man       True    C  Southampton    no  True
freq     577      644    491  537        537   59          644   549   537

## Step 3: Determine the Type of Missing Data
- Discuss with your group: Is the missing data **MCAR** (Missing Completely at Random), **MAR** (Missing at Random), or **MNAR** (Missing Not at Random)?
- Record your reasoning for each column.

In [5]:
# Check missing values by column
missing_count = titanic.isnull().sum()
missing_count.name = 'Count'
missing_count

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
Name: Count, dtype: int64

In [6]:
pd.crosstab(titanic["alive"], titanic["age"].isna(), normalize="index")

age       False     True
alive
no     0.772313  0.227687
yes    0.847953  0.152047

In [7]:
print("which gives the odds ratio (OR) of ", (0.22/0.77) / (0.15/0.85))

which gives the odds ratio (OR) of  1.6190476190476188

In [8]:
pd.crosstab(titanic["alive"], titanic["deck"].isna(), normalize="index")

deck      False     True
alive
no     0.122040  0.877960
yes    0.397661  0.602339

In [9]:
print("which gives the odds ratio (OR) of ", (0.88/0.12) / (0.6 / 0.4))

which gives the odds ratio (OR) of  4.88888888888889

now, compare `age` and `deck` with `pclass`, maybe it tell some more relationship?

In [10]:
age_by_pclass = pd.crosstab(titanic["pclass"], titanic["age"].isna(), normalize="index")
age_by_pclass

age        False     True
pclass
1       0.861111  0.138889
2       0.940217  0.059783
3       0.723014  0.276986

In [11]:
# Odds of missing data: compare each class with First class
print("which gives the odds ratio (OR) for Second vs First class of ", (age_by_pclass.loc[2, True] / age_by_pclass.loc[2, False]) / (age_by_pclass.loc[1, True] / age_by_pclass.loc[1, False]))
print("which gives the odds ratio (OR) for Third vs First class of ", (age_by_pclass.loc[3, True] / age_by_pclass.loc[3, False]) / (age_by_pclass.loc[1, True] / age_by_pclass.loc[1, False]))

which gives the odds ratio (OR) for Second vs First class of  0.39421965317919083
which gives the odds ratio (OR) for Third vs First class of  2.375211267605634

In [12]:
deck_by_pclass = pd.crosstab(titanic["pclass"], titanic["deck"].isna(), normalize="index")
deck_by_pclass

deck       False     True
pclass
1       0.810185  0.189815
2       0.086957  0.913043
3       0.024440  0.975560

In [13]:
# Odds of missing data: compare each class with First class
print("which gives the odds ratio (OR) for Second vs First class of ", (deck_by_pclass.loc[2, True] / deck_by_pclass.loc[2, False]) / (deck_by_pclass.loc[1, True] / deck_by_pclass.loc[1, False]))
print("which gives the odds ratio (OR) for Third vs First class of ", (deck_by_pclass.loc[3, True] / deck_by_pclass.loc[3, False]) / (deck_by_pclass.loc[1, True] / deck_by_pclass.loc[1, False]))

which gives the odds ratio (OR) for Second vs First class of  44.8170731707317
which gives the odds ratio (OR) for Third vs First class of  170.3760162601626

*Write your answer here.*
> - `age` and `deck` could be either MNAR or MAR, as our evidence suggest the two variable is tied to `alive` and `pclass`, shows an association. From the result, most OR value is far from 1.0, which suggest that missing-ness odds of our target variable (`age` and `deck`) is tied to the two variable we use to test it. 
>
> - while `embark_town` got too few data points to conclude.

## Step 4: Determine the Amount of Missing Data
- Calculate the percentage of missing data in each column.
- Decide which columns are most affected.

In [14]:
missing_percent = titanic.isnull().mean() * 100
missing_percent.name = 'Percent'
missing_percent.round(2)

survived        0.00
pclass          0.00
sex             0.00
age            19.87
sibsp           0.00
parch           0.00
fare            0.00
embarked        0.22
class           0.00
who             0.00
adult_male      0.00
deck           77.22
embark_town     0.22
alive           0.00
alone           0.00
Name: Percent, dtype: float64

*Write your answer here.*

- `deck`: 77.22%, most affected column
- `age`: 19.87%, affected a lot
- `embarked` and `embark_town`: 0.22%
- other columns: 0%

## Step 5: Decide How to Handle Missing Data
- Discuss strategies: drop rows, fill with mean/median/mode, forward fill, backward fill, or create a new category.
- Record your chosen method for each column.
- Document any external searches or AI prompts you used.

> - `embarked` and `embark_town`: I'd drop the column.
>
> - `age`: As the data is not sorted in any sense, interpolation probably won't work. maybe use a 'smart' method like KNN or regression. 
>
> - `deck`: About 77% is missing, and it is categorical, so filling with a median doesn't make sense. KNN classification might be possible, but with so much missing data, I don't expect it to be very reliable. Maybe check `pclass` and `fare`, then manually define conditions to match passengers with known decks and estimate the missing ones, or checking with actual historical records is another approach that might work.

## Step 6: Apply Your Methods
- Implement the cleaning strategies you decided.
- Example: `titanic['age'].fillna(titanic['age'].median(), inplace=True)`

In [15]:
# Example cleaning (students should modify based on group decision)
titanic_cleaned = titanic.copy()

# titanic_cleaned['age'].fillna(titanic_cleaned['age'].median(), inplace=True)
titanic_cleaned['age'] = titanic_cleaned['age'].fillna(
    titanic_cleaned['age'].median(), 
    # inplace=True
)

# titanic_cleaned['embarked'].fillna('Unknown', inplace=True)
titanic_cleaned['embarked'] = titanic_cleaned['embarked'].fillna('Unknown')

titanic_cleaned.drop(columns=['deck'], inplace=True)  # Example: drop column with too many missing values

## Step 7: Run Descriptive Statistics Again

In [16]:
# Descriptive statistics of numerical columns
titanic_cleaned.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
# Descriptive statistics of categorial columns
titanic_cleaned.select_dtypes(include=['object', 'category', 'bool']).describe()

/var/folders/x1/q5ftwsxd63l56l4dr27_lk2r0000gn/T/ipykernel_30090/923239583.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  titanic_cleaned.select_dtypes(include=['object', 'category', 'bool']).describe()

         sex embarked  class  who adult_male  embark_town alive alone
count    891      891    891  891        891          889   891   891
unique     2        4      3    3          2            3     2     2
top     male        S  Third  man       True  Southampton    no  True
freq     577      644    491  537        537          644   549   537

## Step 8: Compare Original vs Cleaned Statistics
- Discuss differences in mean, median, and distributions.
- Record your observations.

*Write your comparison here.*

## Step 9: Conclude
- Reflect on whether your chosen methods were suitable.
- Would another approach have been better?

*Write your conclusion here.*

## Step 10: Ask Generative AI for Suggestions
- Example prompt: *"Suggest better ways to handle missing data in the Titanic dataset."*
- Record the AI’s suggestions and evaluate them.
- Compare these AI's suggestions to the previous AI's.
- Note how effective the AI was in helping you overall.

*Write your discussion here.*